# Auto-generated by json_to_ftl.py

## n1
# @p=1|name @t=array
n1--name = Anvil

# @p=1|subtitle @t=str
n1--subtitle = {""}

# @p=1|description @t=array
n1--description =
    A heavy anvil from a blacksmith’s workshop, somehow carried⎵
    around as equipment. Its hardness and weight make it perfect for
    sharpening weapons, though it may be tough for the inexperienced...

# @p=1|ability @t=array
n1--ability =
    Senpo changes to pulling out the anvil to repair weapons
    Cannot repair magic weapons or golden-quality weapons

## n2
# @p=2|name @t=array
n2--name = Jeweled Armament

# @p=2|subtitle @t=str
n2--subtitle = {""}

# @p=2|description @t=array
n2--description =
    Minerals slumbering underground are good alchemical media
    This dagger-shaped magitech device channels the power of precious⎵
    gems, but its costly use led most alchemists to abandon it…

# @p=2|ability @t=array
n2--ability =
    Randomly consumes a gem on attack to charge and enhance damage
    The more precious the gem, the greater the added magic damage

## n3
# @p=3|name @t=array
n3--name = Odd Hair Accessory

# @p=3|subtitle @t=str
n3--subtitle = {""}

# @p=3|description @t=array
n3--description =
    A hair accessory adorned with an unusual ornament
    Is it a rabbit… or a bun…?

# @p=3|ability @t=array
n3--ability = {""}

## n5
# @p=5|name @t=array
n5--name = Safety Gloves

# @p=5|subtitle @t=str
n5--subtitle = {""}

# @p=5|description @t=array
n5--description =
    Protective gloves made from insulating materials,⎵
    originally used by workers as everyday safety gear. Surprisingly,⎵
    they also provide strong resistance against magical attacks...

# @p=5|ability @t=array
n5--ability = Greatly reduces the effect of lightning when equipped

## n6
# @p=6|name @t=array
n6--name = Birth of Misfortune

# @p=6|subtitle @t=str
n6--subtitle = {""}

# @p=6|description @t=array
n6--description =
    Parasitized by a Philosopher Stone, a weak creature was forcibly
    infused with endless vitality, endlessly cycling between life and
    death until madness took over. Even removed, this power remains

# @p=6|ability @t=array
n6--ability =
    Increases HP. Enhances HP recovery effects by 25%
    Grants automatic regeneration when equipped

## n7
# @p=7|name @t=array
n7--name = Cursed Fetus

# @p=7|subtitle @t=str
n7--subtitle = {""}

# @p=7|description @t=array
n7--description =
    An undeveloped cursed fetus that, despite everything,
    remains alive.Its intense will to survive and overflowing
    vitality can even influence its bearer

# @p=7|ability @t=array
n7--ability = Increases HP. Enhances HP recovery effects by 20%

## n8
# @p=8|name @t=array
n8--name = Mana Crystal Cluster

# @p=8|subtitle @t=str
n8--subtitle = {""}

# @p=8|description @t=array
n8--description =
    A mineral shaped by the Great Labyrinth, containing trace mana
    Carrying it enhances magical understanding

# @p=8|ability @t=array
n8--ability =
    Equipping it boosts casting speed and magic power
    Magical weapons’ attacks deal an extra 5% magic damage

## n9
# @p=9|name @t=array
n9--name = Abyssal Mana Cluster

# @p=9|subtitle @t=str
n9--subtitle = {""}

# @p=9|description @t=array
n9--description =
    A rare cluster infused with dense mana,
    radiating palpable magical waves. Highly sought after by alchemists

# @p=9|ability @t=array
n9--ability =
    Equipping it boosts casting speed and magic power
    Magical weapons’ attacks deal an extra 10% magic damage

## n10
# @p=10|name @t=array
n10--name = Focus Circlet

# @p=10|subtitle @t=str
n10--subtitle = {""}

# @p=10|description @t=array
n10--description =
    A circlet worn by the great sage during their youth as an
    adventurer. It helps focus the mind and blocks external distractions

# @p=10|ability @t=array
n10--ability =
    Immune to Stun
    Enhances magic power and casting scale

## n11
# @p=11|name @t=array
n11--name = Mana Draining Gloves

# @p=11|subtitle @t=str
n11--subtitle = {""}

# @p=11|description @t=array
n11--description =
    Gloves worn by the great sage during their youth as
    an adventurer. They gather mana naturally,
    imbuing weapons with magical properties

# @p=11|ability @t=array
n11--ability =
    When equipped, the held weapon transforms into a magical weapon
    Magical weapons’ attacks deal an extra 30% magic damage

## n12
# @p=12|name @t=array
n12--name = Borrowed Neko Claws

# @p=12|subtitle @t=array
n12--subtitle = ⎵"...Meow~?"

# @p=12|description @t=array
n12--description =
    Neko claws hidden inside a Neko Slime, seemingly infused
    with a cat’s spirit. Equipping them boosts your agility!

# @p=12|ability @t=array
n12--ability = Increases attack power and attack speed

## n13
# @p=13|name @t=array
n13--name = Borrowed Neko Paws

# @p=13|subtitle @t=array
n13--subtitle = ⎵"...Meow~?"

# @p=13|description @t=array
n13--description =
    Neko paws hidden inside a Neko Slime, seemingly infused
    with a cat’s spirit. Equipping them boosts your agility!

# @p=13|ability @t=array
n13--ability = Increases attack and movement speed, reduces Senpo cooldown

## n14
# @p=14|name @t=array
n14--name = Fragrant Grass Ring

# @p=14|subtitle @t=str
n14--subtitle = {""}

# @p=14|description @t=array
n14--description =
    A ring woven from leaves and rhizomes, emitting a herbal scent
    Once a charm for travelers, it symbolizes vitality and energy

# @p=14|ability @t=array
n14--ability =
    Max HP +\c[29]{"${QJ.MPMZ.tl.ex_fragrantGrassRingEffectResolve()}"}\c[0]
    Wearing multiple of this gear enhances its effect

## n15
# @p=15|name @t=array
n15--name = Neko Plush Suit

# @p=15|subtitle @t=str
n15--subtitle = {""}

# @p=15|description @t=array
n15--description =
    A soft and cuddly cat plush costume — fluffy and oversized
    Its roomy design wraps you up and even hides extra goodies~

# @p=15|ability @t=array
n15--ability =
    Extra carry capacity for weapons +10
    Extra carry capacity for gears +20

## n16
# @p=16|name @t=array
n16--name = Piercing Spike Helmet

# @p=16|subtitle @t=str
n16--subtitle = {""}

# @p=16|description @t=array
n16--description =
    A spiked metal armor exuding danger from every angle,
    offering solid defense and automatically damaging nearby enemies

# @p=16|ability @t=array
n16--ability = Automatically damages nearby enemies

## n17
# @p=17|name @t=array
n17--name = Piercing Spike Armour

# @p=17|subtitle @t=str
n17--subtitle = {""}

# @p=17|description @t=array
n17--description =
    A spiked metal armor exuding danger from every angle,
    offering solid defense and automatically damaging nearby enemies

# @p=17|ability @t=array
n17--ability = Automatically damages nearby enemies

## n18
# @p=18|name @t=array
n18--name = Piercing Spike Gauntlets

# @p=18|subtitle @t=str
n18--subtitle = {""}

# @p=18|description @t=array
n18--description =
    A spiked metal armor exuding danger from every angle,
    offering solid defense and automatically damaging nearby enemies

# @p=18|ability @t=array
n18--ability = Automatically damages nearby enemies when attacking

## n19
# @p=19|name @t=array
n19--name = Piercing Spike Boots

# @p=19|subtitle @t=str
n19--subtitle = {""}

# @p=19|description @t=array
n19--description =
    A spiked metal armor exuding danger from every angle,
    offering solid defense and automatically damaging nearby enemies

# @p=19|ability @t=array
n19--ability = Automatically damages nearby enemies when moving

## n20
# @p=20|name @t=array
n20--name = Knight's Helmet

# @p=20|subtitle @t=str
n20--subtitle = {""}

# @p=20|description @t=array
n20--description =
    The standard armor of court knights. Its ornate and sturdy design
    symbolizes their adherence to the chivalric code

# @p=20|ability @t=array
n20--ability = Increases defense when HP is below \c[10]30%\c[0]

## n21
# @p=21|name @t=array
n21--name = Knight's Armour

# @p=21|subtitle @t=str
n21--subtitle = {""}

# @p=21|description @t=array
n21--description =
    The standard armor of court knights. Its ornate and sturdy design
    symbolizes their adherence to the chivalric code

# @p=21|ability @t=array
n21--ability = Increases defense when HP is below \c[10]30%\c[0]

## n22
# @p=22|name @t=array
n22--name = Knight's Gauntlets

# @p=22|subtitle @t=str
n22--subtitle = {""}

# @p=22|description @t=array
n22--description =
    The standard armor of court knights. Its ornate and sturdy design
    symbolizes their adherence to the chivalric code

# @p=22|ability @t=array
n22--ability = Increases attack and defense when HP is below \c[10]30%\c[0]

## n23
# @p=23|name @t=array
n23--name = Knight's Greaves

# @p=23|subtitle @t=str
n23--subtitle = {""}

# @p=23|description @t=array
n23--description =
    The standard armor of court knights. Its ornate and sturdy design
    symbolizes their adherence to the chivalric code

# @p=23|ability @t=array
n23--ability = Increases movement speed when HP is below \c[10]30%\c[0]

## n24
# @p=24|name @t=array
n24--name = Hunter’s Garb

# @p=24|subtitle @t=str
n24--subtitle = {""}

# @p=24|description @t=array
n24--description =
    Stitched from thick hide and tough linen, it was once the everyday⎵
    gear of forest hunters. Though defense is limited, it’s light and⎵
    flexible, letting the wearer move quickly through the woods

# @p=24|ability @t=array
n24--ability = Slowly regenerates HP when standing on grassy terrain

## n25
# @p=25|name @t=array
n25--name = Hunter’s Belt

# @p=25|subtitle @t=str
n25--subtitle = {""}

# @p=25|description @t=array
n25--description =
    Crafted from sturdy leather and adorned with durable buckles
    and pouches. Once essential for forest hunters on their journeys,⎵
    it remains light and unburdensome even during long treks

# @p=25|ability @t=array
n25--ability =
    Max HP +20, movement speed increased
    Extra carry capacity for weapons +5, for gear +5

## n26
# @p=26|name @t=array
n26--name = Feather of Firebird

# @p=26|subtitle @t=array
n26--subtitle = {""}

# @p=26|description @t=array
n26--description =
    A Firebird feather.
    symbolizing eternal life, still burning with a warm flame.
    Even a single feather holds the power to revive the dead.

# @p=26|ability @t=array
n26--ability =
    Activates when HP drops to zero, fully restores HP
    The item is destroyed after activation

## n27
# @p=27|name @t=array
n27--name = Toilet Paper

# @p=27|subtitle @t=str
n27--subtitle = {""}

# @p=27|description @t=array
n27--description =
    A Toilet Paper take from Home
    A handy item for adventurers who suddenly need
    a toilet break in a dangerous dungeon

# @p=27|ability @t=array
n27--ability = Reduces Bleed damage taken by \c[10]30%\c[0]

## n28
# @p=28|name @t=array
n28--name = Oni Hand

# @p=28|subtitle @t=array
n28--subtitle = {""}

# @p=28|description @t=array
n28--description =
    A massive arm brimming with the brute strength of the Oni clan
    It symbolizes a power so fierce it can easily crush solid rock
    For humans, it is a force far too difficult to control

# @p=28|ability @t=array
n28--ability =
    Physical attack power +100%. Attack speed decreases
    Weapons are more likely to break during attacks

## n29
# @p=29|name @t=array
n29--name = Saucy Jacky

# @p=29|subtitle @t=array
n29--subtitle = "This one craves screams..."

# @p=29|description @t=array
n29--description =
    One of the deadly weapons of a notorious killer,
    still twitching with anticipation

# @p=29|ability @t=array
n29--ability = Deals more damage to lower HP foes, up to \c[10]30%\c[0]

## n30
# @p=30|name @t=array
n30--name = Hunter's Dagger

# @p=30|subtitle @t=array
n30--subtitle = "Death from the muzzle, fortune from the blade"

# @p=30|description @t=array
n30--description =
    A small, sharp dagger that fits easily in a boot
    To a hunter, it always draws out the prey’s final offering

# @p=30|ability @t=array
n30--ability = Increases chances of meat drops

## n31
# @p=31|name @t=array
n31--name = Misty Night Phantom

# @p=31|subtitle @t=array
n31--subtitle = "This one longs to vanish..."

# @p=31|description @t=array
n31--description =
    One of the deadly tools of a notorious murderer,
    crafted to conceal its presence

# @p=31|ability @t=array
n31--ability =
    Periodically enters an invisible state
    Assassinations while invisible deal double damage

## n32
# @p=32|name @t=array
n32--name = Neko Punch

# @p=32|subtitle @t=str
n32--subtitle = {""}

# @p=32|description @t=array
n32--description =
    "Hyaa—!! Don’t mess with me nya!"
    Soft-padded cat paw gloves, the prized weapon of a certain catgirl
    Wearing them grants feline agility—and a craving for fish…

# @p=32|ability @t=array
n32--ability =
    Attack speed increased. Extra attack hits +1
    Chance of extra attack hits triggering special effects is halved

## n33
# @p=33|name @t=array
n33--name = Apple Headgear

# @p=33|subtitle @t=str
n33--subtitle = {""}

# @p=33|description @t=array
n33--description =
    A headgear made from apples, so you can't
    really expect any defense. But the apples are so delicious

# @p=33|ability @t=array
n33--ability = There’s a chance to activate healing when injured

## n34
# @p=34|name @t=array
n34--name = Sharpblade Ring

# @p=34|subtitle @t=str
n34--subtitle = {""}

# @p=34|description @t=array
n34--description =
    Legend says an adventurer, too afraid of fighting barehanded,⎵
    embedded a sword into a ring. It’s far too small to use,⎵
    but it sure boosts one’s presence

# @p=34|ability @t=array
n34--ability = Physical attack power +15%

## n35
# @p=35|name @t=array
n35--name = Wakizashi

# @p=35|subtitle @t=str
n35--subtitle = {""}

# @p=35|description @t=array
n35--description =
    A finely crafted short blade, often carried by foreign samurai⎵
    as a sidearm. Though short, its edge can tear flesh wide open,
    leaving wounds that won’t easily stop bleeding

# @p=35|ability @t=array
n35--ability =
    Normal attack count with melee weapons +1
    Extra attack has a chance to inflict Bleed

## n36
# @p=36|name @t=array
n36--name = Maneki Neko

# @p=36|subtitle @t=str
n36--subtitle = {""}

# @p=36|description @t=array
n36--description =
    A greedy little Servant with a perpetually unsatisfied look
    It eagerly gathers all dropped items, regardless of their value

# @p=36|ability @t=array
n36--ability =
    Maneki Neko automatically collects all types of drops for you
    Equipping multiple will only increase the collection range

## n37
# @p=37|name @t=array
n37--name = ⎵Piggy Bank

# @p=37|subtitle @t=str
n37--subtitle = {""}

# @p=37|description @t=array
n37--description =
    A cute Servant that stores collected money
    Something might happen when full, but for now, it's just fragile

# @p=37|ability @t=array
n37--ability =
    Happily collects money. Current savings: \c[6]{"${$gameSelfVariables.value([1, 110, 'deposit'])}"}\c[0]yen!
    Easily breaks when attacked, losing all stored money

## n38
# @p=38|name @t=array
n38--name = ⎵Greedy Piggy Bank

# @p=38|subtitle @t=str
n38--subtitle = {""}

# @p=38|description @t=array
n38--description =
    A piggy bank overflowing with wealth, a dream come true
    Yet, even with a belly full of gold, its greed knows no bounds

# @p=38|ability @t=array
n38--ability =
    Emits Mamon’s Demand aura. Current savings: \c[6]{"${$gameSelfVariables.value([1, 110, 'deposit'])}"}\c[0]yen!
    Collects money endlessly, spitting out interest every 10 seconds

## n39
# @p=39|name @t=array
n39--name = Green Turtle Shell

# @p=39|subtitle @t=str
n39--subtitle = {""}

# @p=39|description @t=array
n39--description =
    A tough and heavy turtle shell
    Carrying it on land makes it impossible to lift your feet…!

# @p=39|ability @t=array
n39--ability = Slows movement speed, but increases swimming speed

## n40
# @p=40|name @t=array
n40--name = Maid Uniform

# @p=40|subtitle @t=str
n40--subtitle = {""}

# @p=40|description @t=array
n40--description =
    A trophy obtained after teaching a lesson to the mischievous
    rabbit-eared girl. It still carries the scent of dirt and carrots

# @p=40|ability @t=array
n40--ability =
    When equipped, disguises as a monster but cannot attack
    Equipping it makes you best friends with Maid Bunny

## n41
# @p=41|name @t=array
n41--name = Moe Bunny Ears

# @p=41|subtitle @t=str
n41--subtitle = {""}

# @p=41|description @t=array
n41--description =
    A detachable bunny ear accessory
    No matter who wears it, they’ll look absolutely adorable!

# @p=41|ability @t=array
n41--ability = Blessed with luck! Items are more likely to drop!

## n42
# @p=42|name @t=array
n42--name = Bomb Fiend's Soul

# @p=42|subtitle @t=array
n42--subtitle = "Explo————sion!!"

# @p=42|description @t=array
n42--description =
    A will that sacrificed everything for explosions
    Now that you bear it, won’t you strive for even bigger blasts?

# @p=42|ability @t=array
n42--ability =
    Small chance to trigger an explosion when attacking or hit
    Reduce self-taken explosion damage by 50%

## n43
# @p=43|name @t=array
n43--name = Bladekeepers’ Badge

# @p=43|subtitle @t=array
n43--subtitle =
    "You adventurers make me sick!
    Swinging your blades only to kill, never caring about their pain!"

# @p=43|description @t=array
n43--description = A badge worn only by comrades who believe in weapon preservation

# @p=43|ability @t=array
n43--ability =
    Attack power -20%, max attack capped at 200
    Reduces all weapon durability loss by 20%

## n44
# @p=44|name @t=array
n44--name = ◉▽◉

# @p=44|subtitle @t=array
n44--subtitle = "The Sacabambaspis has seen it all before."

# @p=44|description @t=array
n44--description =
    A legendary ancient Servant—though it’s a fish, it can’t swim
    It has tough skin, and its special move is a Cyclone Jet Cannon!

# @p=44|ability @t=array
n44--ability =
    Can lift up the Saccabankame turtle and throw it as an attack
    Once it falls into the water, it can’t get back out...

## n45
# @p=45|name @t=array
n45--name = Venomous Embrace

# @p=45|subtitle @t=array
n45--subtitle = "This dagger's loaded with deadly poison, y'know— (lick"

# @p=45|description @t=array
n45--description = A poisonous magical shortsword—keep your distance

# @p=45|ability @t=array
n45--ability =
    An auto-orbiting Servant
    High chance to inflict Poison on contact

## n46
# @p=46|name @t=array
n46--name = Fist of Fury

# @p=46|subtitle @t=array
n46--subtitle = "Left hand hits hard, right hand hits harder."

# @p=46|description @t=array
n46--description =
    A powerful magical fist
    Seething with unknown rage, it remains tightly clenched…

# @p=46|ability @t=array
n46--ability =
    An auto-orbiting Servant
    Knocks back any enemy it touches

## n47
# @p=47|name @t=array
n47--name = Xerise’s Cursed Hand

# @p=47|subtitle @t=str
n47--subtitle = {""}

# @p=47|description @t=array
n47--description =
    A severed hand imbued with undead power
    Even without a body, it remains lively and aggressive

# @p=47|ability @t=array
n47--ability =
    An auto-orbiting Servant
    Curses any target it points its middle finger at

## n48
# @p=48|name @t=array
n48--name = Chain SpellBinding Contract

# @p=48|subtitle @t=array
n48--subtitle =
    "When the one you love dies, you must take your own life.
    When the one you love dies, there is no other way."

# @p=48|description @t=array
n48--description = To save his familiar, a certain alchemist forged this contract…

# @p=48|ability @t=array
n48--ability =
    Link with your servant—any damage they take will be yours
    Each linked servant grants you a healing effect

## n49
# @p=49|name @t=array
n49--name = Red Horn

# @p=49|subtitle @t=array
n49--subtitle = "Don't you ever stop！"

# @p=49|description @t=array
n49--description =
    A crimson horn filled with the Jackalope’s magic
    If magic could be supplied endlessly, it might keep accelerating⎵
    until it became a comet streaking across the sky!

# @p=49|ability @t=array
n49--ability =
    When fully charged, Senpo has no cooldown and moves faster
    Once the charge is depleted, it will auto-recharge

## n50
# @p=50|name @t=array
n50--name = Potato Chips

# @p=50|subtitle @t=str
n50--subtitle = {""}

# @p=50|description @t=array
n50--description =
    Freshly fried with a warm,
    savory aroma. Watch out for seagulls!

# @p=50|ability @t=array
n50--ability = Attracts seagulls that steal your chips

## n52
# @p=52|name @t=array
n52--name = Shadowcrawler Gift

# @p=52|subtitle @t=str
n52--subtitle = {""}

# @p=52|description @t=array
n52--description =
    Said to be a symbol from the depths where shadows creep
    holding it makes you feel as if something is⎵
    quietly writhing behind you—

# @p=52|ability @t=array
n52--ability =
    Movement speed increases
    Gain the attention of ▓▓▓▓▓▓▓

## n53
# @p=53|name @t=array
n53--name = Hanged Man's Bone Ring

# @p=53|subtitle @t=str
n53--subtitle = {""}

# @p=53|description @t=array
n53--description =
    A ring made from the bones of the deceased Hanged Man
    Though most of its power is lost,
    it still grants the wearer a bit of freedom from gravity

# @p=53|ability @t=array
n53--ability = Reduces fall damage by 66%

## n54
# @p=54|name @t=array
n54--name = Incomplete Golden Grail

# @p=54|subtitle @t=str
n54--subtitle = {""}

# @p=54|description @t=array
n54--description =
    A saint’s relic yet to be filled, it blesses the holder with
    immense luck. The source of this blessing remains unknown,
    as it quietly awaits the day it will be complete

# @p=54|ability @t=array
n54--ability = Greatly increases luck. Doubles money earned

## n55
# @p=55|name @t=array
n55--name = Arsonist’s Gloves

# @p=55|subtitle @t=array
n55--subtitle = "Hah, Such filthy fireworks."

# @p=55|description @t=array
n55--description = Thick, heatproof gloves reeking of gunpowder

# @p=55|ability @t=array
n55--ability =
    +30% explosion radius for self-triggered bombs
    Bombs have a chance to trigger chain explosions

## n56
# @p=56|name @t=array
n56--name = Saint Maiden’s Mercy

# @p=56|subtitle @t=array
n56--subtitle = "Good child, good child..."

# @p=56|description @t=array
n56--description =
    One of the nun's attires, silky smooth to the touch, unforgettable
    Holy radiance flows through its fibers, offering comfort

# @p=56|ability @t=array
n56--ability =
    Forcibly enters Sage Mode
    Gain more affinity when patting \str[120]’s head

## n57
# @p=57|name @t=array
n57--name = Ichigo Wo Torimodose!!

# @p=57|subtitle @t=array
n57--subtitle = {""}

# @p=57|description @t=array
n57--description =
    ASABA, consumed by grief over the lost strawberry,⎵
    unleashes his ultimate art. Once targeted, you’re swallowed
    by an unavoidable storm of combos… But sorrow lingers—
    burned by fate’s emotions, you too inherit this forbidden technique!⎵

# @p=57|ability @t=array
n57--ability =
    Unleash a special move with the right command⎵
    The lower your HP, the stronger the special move

## n59
# @p=59|name @t=array
n59--name = Rubrum Pendant

# @p=59|subtitle @t=array
n59--subtitle = {""}

# @p=59|description @t=array
n59--description =
    The Fallen Magician’s Precious Relic.⎵
    A pendant crafted from a small amount of Philosopher's Fragment⎵
    imbued with a faint yet everlasting alchemical power

# @p=59|ability @t=array
n59--ability =
    Boosts magic attack based on held Philosopher's Fragment count
    Reduces weapon durability use when casting magic by \c[6]24%\c[0]

## n60
# @p=60|name @t=array
n60--name = Fallen Mage's Circlet

# @p=60|subtitle @t=str
n60--subtitle = {""}

# @p=60|description @t=array
n60--description =
    A cursed circlet tainted by dark magic,
    haunted by a stubborn grudge that gnaws at the flesh

# @p=60|ability @t=array
n60--ability =
    Magic attack power +100%
    Max HP -50%

## n61
# @p=61|name @t=array
n61--name = Fallen Mage's Cloak

# @p=61|subtitle @t=str
n61--subtitle = {""}

# @p=61|description @t=array
n61--description =
    A cursed cloak tainted by dark magic,
    haunted by a vengeful spirit craving retribution

# @p=61|ability @t=array
n61--ability =
    Afterimages created by Senpo linger longer
    Objects touched by them are frozen in place

## n62
# @p=62|name @t=array
n62--name = Fallen Mage's Gloves

# @p=62|subtitle @t=str
n62--subtitle = {""}

# @p=62|description @t=array
n62--description =
    Cursed gloves tainted by dark magic,
    infused with a vengeful spirit eager to attack

# @p=62|ability @t=array
n62--ability = Projectiles track nearby enemies

## n63
# @p=63|name @t=array
n63--name = Fallen Mage's Shoes

# @p=63|subtitle @t=str
n63--subtitle = {""}

# @p=63|description @t=array
n63--description =
    Cursed shoes tainted by dark magic,
    infused with a vengeful spirit that grants ghost-like agility

# @p=63|ability @t=array
n63--ability = Boosts movement speed, grants void state when using Senpo

## n65
# @p=65|name @t=array
n65--name = Determination Headband

# @p=65|subtitle @t=array
n65--subtitle = "Who the hell do you think I am!?"

# @p=65|description @t=array
n65--description =
    A headband that stirs passion when worn
    No real effect, but its unyielding spirit is unmatched

# @p=65|ability @t=array
n65--ability =
    reduces abnormal status chance
    Has a small chance to resist fatal damage

## n67
# @p=67|name @t=array
n67--name = Martial Artist's Bracers

# @p=67|subtitle @t=str
n67--subtitle = {""}

# @p=67|description @t=array
n67--description =
    Bandaged bracers worn by martial artists during sparring
    They protect joints while improving movement precision

# @p=67|ability @t=array
n67--ability =
    -12% weapon durability consumption
    Increased attack speed & boosted unarmed combo damage

## n68
# @p=68|name @t=array
n68--name = Martial Artist's Shoes

# @p=68|subtitle @t=str
n68--subtitle = {""}

# @p=68|description @t=array
n68--description =
    Shoes commonly worn by martial artists who have
    mastered their craft, radiating a powerful aura

# @p=68|ability @t=array
n68--ability = Movement speed increased. Senpo enhanced

## n69
# @p=69|name @t=array
n69--name = Face Breaker

# @p=69|subtitle @t=array
n69--subtitle = "Damn it... I just wanna punch someone in the face...!"

# @p=69|description @t=array
n69--description =
    Punching gloves left behind by a legendary boxer.
    You can still feel the overwhelming force lingering on them.

# @p=69|ability @t=array
n69--ability =
    Cannot use weapons while equipped
    Punch attacks may deal bonus damage based on target HP

## n70
# @p=70|name @t=array
n70--name = Scarecrow's Heart

# @p=70|subtitle @t=str
n70--subtitle = {""}

# @p=70|description @t=array
n70--description =
    A hollow body of a scarecrow
    No warmth, no heartbeat—yet it can live in your place

# @p=70|ability @t=array
n70--ability =
    Prevents all forms of HP recovery while equipped
    At 0 HP, you remain active a bit longer before falling

## n73
# @p=73|name @t=array
n73--name = Lava Ring

# @p=73|subtitle @t=str
n73--subtitle = {""}

# @p=73|description @t=array
n73--description =
    A ring forged from rock flowing with scorching magma
    Wearing it eases the pain from both frost and flame

# @p=73|ability @t=array
n73--ability =
    Greatly reduces the chance of being frozen
    Reduces the chance of being burned

## n74
# @p=74|name @t=array
n74--name = Volumen Salamandrae

# @p=74|subtitle @t=array
n74--subtitle = "Yes, they do like chili peppers..."

# @p=74|description @t=array
n74--description =
    A grimoire bound with salamander scales. Though it resembles
    an encyclopedia, its records of volcano-dwelling salamanders⎵
    grant deeper insight into fire when studied.

# @p=74|ability @t=array
n74--ability = Strengthens the damage and form of fire-element magic

## n75
# @p=75|name @t=array
n75--name = Demon Eyeball

# @p=75|subtitle @t=str
n75--subtitle = {""}

# @p=75|description @t=array
n75--description =
    An eyeball taken from a demon. It’s still watching. ⎵
    Demons skilled at manipulating minds often possess the ability⎵
    to see through things. Perhaps it allows you to notice details⎵
    that would otherwise be overlooked...

# @p=75|ability @t=array
n75--ability = Reveals hidden objects and paths while equipped

## n77
# @p=77|name @t=array
n77--name = A Maiden's Prayer

# @p=77|subtitle @t=array
n77--subtitle = "Fish… so many fish… piles of salmon…"

# @p=77|description @t=array
n77--description =
    A prayer offered by an archdemon obsessed with eating salmon
    Saying it can warp reality might be a bit of an exaggeration…
    but she is genuinely, earnestly waiting for offerings to arrive

# @p=77|ability @t=array
n77--ability = More likely to obtain \ii[142] and \ii[143]

## n80
# @p=80|name @t=array
n80--name = Royal Decree

# @p=80|subtitle @t=str
n80--subtitle = {""}

# @p=80|description @t=array
n80--description =
    A ring symbolizing the supreme glory of a true king
    Greatly boosts follower morale!

# @p=80|ability @t=array
n80--ability =
    Slightly increases all stats
    Enlarges all servants and enhances their special attributes

## n100
# @p=100|name @t=array
n100--name = Unit I Nexus

# @p=100|subtitle @t=str
n100--subtitle = {""}

# @p=100|description @t=array
n100--description =
    A core far more advanced than modern tech, its surface glowing⎵
    with mysterious energy circuits. Even with most parts missing,⎵
    it still shows incredible computational and sensing power

# @p=100|ability @t=array
n100--ability =
    Grants area detection when equipped
    Detected object types increase as the core’s level rises

## n125
# @p=125|name @t=array
n125--name = Atsu Atsu Bouzu

# @p=125|subtitle @t=str
n125--subtitle = {""}

# @p=125|description @t=array
n125--description =
    A cloth doll made with someone's heartfelt prayers. It carries
    wishes, bringing slight changes to regular weather patterns
    However, The doll quietly disappears afterward

# @p=125|ability @t=array
n125--ability = Ensures scorching hot weather the next day when equipped

## n126
# @p=126|name @t=array
n126--name = Teru Teru Bouzu

# @p=126|subtitle @t=str
n126--subtitle = {""}

# @p=126|description @t=array
n126--description =
    A cloth doll made with someone's heartfelt prayers. It carries
    wishes, bringing slight changes to regular weather patterns
    However, The doll quietly disappears afterward

# @p=126|ability @t=array
n126--ability = Ensures sunny weather the next day when equipped

## n127
# @p=127|name @t=array
n127--name = Kumo Kumo Bouzu

# @p=127|subtitle @t=str
n127--subtitle = {""}

# @p=127|description @t=array
n127--description =
    A cloth doll made with someone's heartfelt prayers. It carries
    wishes, bringing slight changes to regular weather patterns
    However, The doll quietly disappears afterward

# @p=127|ability @t=array
n127--ability = Ensures cloudy weather the next day when equipped

## n128
# @p=128|name @t=array
n128--name = Ame Ame Bouzu

# @p=128|subtitle @t=str
n128--subtitle = {""}

# @p=128|description @t=array
n128--description =
    A cloth doll made with someone's heartfelt prayers. It carries
    wishes, bringing slight changes to regular weather patterns
    However, The doll quietly disappears afterward

# @p=128|ability @t=array
n128--ability = Ensures rainy weather the next day when equipped

## n129
# @p=129|name @t=array
n129--name = A girl's smile

# @p=129|subtitle @t=array
n129--subtitle = "\str[121], you kept your promise well!"

# @p=129|description @t=array
n129--description =
    The perfect smile finally shown by \str[120]⎵
    who has always admired and worried about \str[121]—
    a smile that becomes his motivation to keep moving forward

# @p=129|ability @t=array
n129--ability = Desire up, all stats increased

## n130
# @p=130|name @t=array
n130--name = \str[120]'s removed panties

# @p=130|subtitle @t=array
n130--subtitle = "It still carries \str[120]'s scent..."

# @p=130|description @t=array
n130--description =
    Panties received from \str[120] due to a misunderstanding
    Although no suitable chance to return it has ever come up,
    deep down inside, a faint sense of joy quietly lingers...

# @p=130|ability @t=array
n130--ability = Automatically regenerates HP when below 50%

## n131
# @p=131|name @t=array
n131--name = Bunny Plush

# @p=131|subtitle @t=array
n131--subtitle = "Waaah—! Don’t break it~~!"

# @p=131|description @t=array
n131--description =
    A stuffed bunny plush that \str[120] always carries in⎵
    her arms, filled with her scent
    Come to think of it… why is this in my hands?

# @p=131|ability @t=array
n131--ability = {""}

## n147
# @p=147|name @t=array
n147--name = Woundplast

# @p=147|subtitle @t=str
n147--subtitle = {""}

# @p=147|description @t=array
n147--description = {""}

# @p=147|ability @t=empty_array
n147--ability = ⊘

## n150
# @p=150|name @t=array
n150--name = Bonus T-shirt

# @p=150|subtitle @t=str
n150--subtitle = {""}

# @p=150|description @t=array
n150--description =
    A custom-made outfit from the knight,
    supposedly for promoting the game
    But I don’t really want to wear it

# @p=150|ability @t=empty_array
n150--ability = ⊘

## n152
# @p=152|name @t=array
n152--name = \str[120]’s Pajamas

# @p=152|subtitle @t=str
n152--subtitle = {""}

# @p=152|description @t=array
n152--description =
    A camisole pajama that \str[120] usually wears,⎵
    decorated with the bows she loves.
    Come to think of it… why is this in my hands?

# @p=152|ability @t=empty_array
n152--ability = ⊘

## n153
# @p=153|name @t=array
n153--name = \str[120]’s Shorts

# @p=153|subtitle @t=str
n153--subtitle = {""}

# @p=153|description @t=array
n153--description =
    Soft and fluffy shorts that \str[120] usually wears,⎵
    decorated with the bows she loves.
    Come to think of it… why is this in my hands?

# @p=153|ability @t=empty_array
n153--ability = ⊘

## n154
# @p=154|name @t=array
n154--name = Blue white panties

# @p=154|subtitle @t=str
n154--subtitle = {""}

# @p=154|description @t=array
n154--description = {""}

# @p=154|ability @t=empty_array
n154--ability = ⊘

## n155
# @p=155|name @t=array
n155--name = Pink white panties

# @p=155|subtitle @t=str
n155--subtitle = {""}

# @p=155|description @t=array
n155--description = {""}

# @p=155|ability @t=empty_array
n155--ability = ⊘

## n156
# @p=156|name @t=array
n156--name = White panties

# @p=156|subtitle @t=str
n156--subtitle = {""}

# @p=156|description @t=array
n156--description = {""}

# @p=156|ability @t=empty_array
n156--ability = ⊘

## n157
# @p=157|name @t=array
n157--name = Woundplast

# @p=157|subtitle @t=str
n157--subtitle = {""}

# @p=157|description @t=array
n157--description = {""}

# @p=157|ability @t=empty_array
n157--ability = ⊘

## n159
# @p=159|name @t=array
n159--name = No panties...

# @p=159|subtitle @t=str
n159--subtitle = {""}

# @p=159|description @t=array
n159--description = {""}

# @p=159|ability @t=empty_array
n159--ability = ⊘

## n296
# @p=296|name @t=array
n296--name = Ruika’s Lucky Mallet

# @p=296|subtitle @t=array
n296--subtitle = "Head Maid Ruika always uses it to bonk the disobedient bunnies."

# @p=296|description @t=array
n296--description =
    A hidden treasure of Maid Bunnies, said to be why they took over the⎵
    market so fast. With a light swing, it grants the wielder’s wishes—
    Adventurers often see it fixing machines broken by troublemakers

# @p=296|ability @t=array
n296--ability = Increases money and item drop rates

## n297
# @p=297|name @t=array
n297--name = Mio’s First Aid Kit

# @p=297|subtitle @t=array
n297--subtitle = "Oh my god! I fell into the hole again!?"

# @p=297|description @t=array
n297--description =
    Originally a tool the admin used to test the healing system
    but he forgot to delete it later. Still, it’s useless⎵
    against instant-death mechanics

# @p=297|ability @t=array
n297--ability = Restores 100% HP per second when equipped

## n298
# @p=298|name @t=array
n298--name = Shiroin’s Golden Finger

# @p=298|subtitle @t=array
n298--subtitle =
    "You know this thing will ruin the game, right?"
    "I know."
    "And you still want to equip it?"
    "Of course."

# @p=298|description @t=array
n298--description = A relic that turns touch to gold — the Bladekeepers’ ultimate dream

# @p=298|ability @t=array
n298--ability = Weapons no longer break from attacks

## n299
# @p=299|name @t=array
n299--name = Absolute Territory

# @p=299|subtitle @t=array
n299--subtitle = {""}

# @p=299|description @t=array
n299--description =
    The sacred space between a girl's miniskirt and thigh-high socks
    Not only does it grant high magic resistance, but also the absurd⎵
    ability to pull out all sorts of items from under the skirt at will

# @p=299|ability @t=array
n299--ability =
    Extra carry capacity for weapons +99
    Extra carry capacity for gears +99

## n300
# @p=300|name @t=array
n300--name = Catalyst Amatoria

# @p=300|subtitle @t=array
n300--subtitle = "Give me your love—! Otherwise, let’s just die together~~~!"

# @p=300|description @t=array
n300--description =
    A forbidden artifact forged by a certain yandere archdemon
    It forcibly makes anyone it touches fall in love with the wearer
    ignoring their will

# @p=300|ability @t=array
n300--ability = Greatly boosts the stats gained when patting \str[120]
