# Auto-generated by json_to_ftl.py

# @p=skillToggle @t=array
skillToggle =
    Activated
    Inactive

# @p=1|name @t=array
n1--name = Magic Storage Bag

# @p=1|subtitle @t=array
n1--subtitle = {""}

# @p=1|description @t=array
n1--description =
    A portable magical tool that allows you to carry⎵
    far more items than usual. However,⎵
    even magical tools have their storage limits..

# @p=1|ability @t=array
n1--ability =
    Weapon capacity: {"${QJ.MPMZ.tl.ex_playerCheckInventory('weapon')}"}
    Gear capacity: {"${QJ.MPMZ.tl.ex_playerCheckInventory('gear')}"}

# @p=2|name @t=array
n2--name = Senpo

# @p=2|subtitle @t=array
n2--subtitle = {""}

# @p=2|description @t=array
n2--description =
    A quick step on the ground covers a short distance,
    allowing you to dodge some attacks. It’s merely a starting dash⎵
    technique, but the user insists on giving it a cool name

# @p=2|ability @t=array
n2--ability = Hold Space Bar to activate

# @p=3|name @t=array
n3--name = Senpo Tachi

# @p=3|subtitle @t=array
n3--subtitle = {""}

# @p=3|description @t=array
n3--description =
    A sword-drawing technique learned from the young Sword Master.
    By combining with SenPo, you unleash a speed-enhanced ⎵
    strike — enough to knock enemies away if timed right.

# @p=3|ability @t=array
n3--ability =
    Left Click during Senpo: Slash, damage scales with speed
    Hold Right Click during Senpo: Charge, effects scale with momentum

# @p=3|mobileAbility @t=array
n3--mobileAbility =
    Tap the skill button to slash, damage scales with movement speed
    Hold the skill button to charge, effect scales with momentum

# @p=4|name @t=array
n4--name = Whirlwind Slash

# @p=4|subtitle @t=array
n4--subtitle = {""}

# @p=4|description @t=array
n4--description =
    Spin while swinging your weapon to launch continuous attacks.⎵
    The attack speed increases over time. For those who aren't great⎵
    with sword techniques, this move is easy to learn and effective.

# @p=4|ability @t=array
n4--ability =
    Hold Right Click to activate the skill
    Cancel during spinning to throw your weapon

# @p=4|mobileAbility @t=array
n4--mobileAbility =
    Hold the skill button to activate the skill
    Cancel while spinning to throw your weapon

# @p=6|name @t=array
n6--name = Lucky Pervert

# @p=6|subtitle @t=array
n6--subtitle = true

# @p=6|description @t=array
n6--description =
    A legendary perverted constitution that activates on its own,⎵
    even without the user realizing it.
    As if blessed and guided by an unseen goddess, irresistible forces⎵
    push you into blush-inducing, heart-pounding fanservice scenarios…!

# @p=6|ability @t=array
n6--ability = Always creates the perfect opportunities to trigger lewd events!

# @p=7|name @t=array
n7--name = Danger Sense

# @p=7|subtitle @t=array
n7--subtitle = {""}

# @p=7|description @t=array
n7--description =
    Often called ‘Mind's Eye’, but it's actually a sense⎵
    sharpened by countless brushes with death.
    In other words, more like a trauma reflex than an actual skill...

# @p=7|ability @t=array
n7--ability = Hover the mouse over the target to view detailed info

# @p=7|mobileAbility @t=array
n7--mobileAbility = Tap the target to view detailed info

# @p=10|name @t=array
n10--name = Breath Concealment

# @p=10|subtitle @t=array
n10--subtitle = true

# @p=10|description @t=array
n10--description =
    A ninja technique. I only picked it up in a rush, but…
    somehow, I got the hang of it pretty quickly.

# @p=10|ability @t=array
n10--ability =
    Press Shift while active to enter stealth
    Reduces the monster's detection range by \c[17]{"${1+$gameParty.leader().skillMasteryLevel(10)}"}\c[108] tile
    Reduces \str[120]’s alert increase rate during peeking by \c[17]{"${15+15*$gameParty.leader().skillMasteryLevel(10)}"}%\c[0]

# @p=11|name @t=array
n11--name = Backstab

# @p=11|subtitle @t=array
n11--subtitle = true

# @p=11|description @t=array
n11--description =
    A ninja technique. Can be activated while in stealth
    Strike an unguarded enemy from behind for massive damage!

# @p=11|ability @t=array
n11--ability =
    Skill Proficiency: \c[6]{"${$gameActors.actor(1).skillMasteryUses(11)}"}\c[0]
    Assassination Damage Bonus: \c[17]{"${Math.round(200 + (2333 - 200) * Math.pow($gameActors.actor(1).skillMasteryLevel(11) / 9, 1.8))}"}%\c[0]

# @p=12|name @t=array
n12--name = Musou Burst Stream

# @p=12|subtitle @t=array
n12--subtitle = {""}

# @p=12|description @t=array
n12--description =
    A secret finisher inherited from ASABA, who embraced sorrow
    In an instant too fast for the eye to see, a hundred strikes land—
    leaving the enemy with nothing but final darkness!

# @p=12|ability @t=array
n12--ability =
    Skill command:  {"{"}⬆⬇⬅⮕⬆⬇{"}"}
    Each use of the skill consumes some HP

# @p=15|name @t=array
n15--name = Crossdressing

# @p=15|subtitle @t=array
n15--subtitle = {""}

# @p=15|description @t=array
n15--description =
    You put on clothes not meant for you… and something inside you⎵
    stirred. No combat bonus—might even mess with your head a little.
    Your companions glance oddly, and enemies might pause… maybe.
    After all, in this world—cuteness is justice!

# @p=15|ability @t=array
n15--ability = Increases Sin based on the number of crossdressing items equipped!

# @p=16|name @t=array
n16--name = Bladekeepers

# @p=16|subtitle @t=array
n16--subtitle = {""}

# @p=16|description @t=array
n16--description =
    "No matter how you swing your weapons!" "We’ll rise to call you out!"
    "To stop the blades from wearing away!" "To protect the dignity of arms!"
    "For we believe the sword is master, and humans are but servants!"
    "The most absurd yet unshakable believers!"
    "We are—Weapon Preservationists—the Bladekeepers!"

# @p=16|ability @t=array
n16--ability = Wearing the badge makes you one of them now

# @p=18|name @t=array
n18--name = Weapon Break

# @p=18|subtitle @t=array
n18--subtitle = {""}

# @p=18|description @t=array
n18--description =
    All weapons have durability limits,⎵
    and since the user isn’t good at precise attacks.
    there’s a risk of breaking them. But when the weapon does break —
    it’ll land a powerful critical hit!

# @p=18|ability @t=array
n18--ability = Final hit damage boost: \c[6]{"${200+(100*$gameActors.actor(1).skillMasteryLevel(48))}"}%\c[0]

# @p=26|name @t=array
n26--name = Swordsmanship Training

# @p=26|subtitle @t=array
n26--subtitle = true

# @p=26|description @t=array
n26--description =
    Sought advice from a swordmaster girl on how to get stronger
    All she said was ‘Just swing your sword 1,000 times every day!’
    —Will that really work!? Anyway, let’s give it a try...

# @p=26|ability @t=array
n26--ability =
    Practice Swings Completed: {"{"}\c[6]{"${QJ.MPMZ.tl.playerSwordsmanshipTraining(1)}"}\c[0]
    Base attack damage of melee weapons increased by \c[6]{"${QJ.MPMZ.tl.playerSwordsmanshipTraining(2)}"}%
