# Auto-generated by json_to_ftl.py

# @k=skillToggle
skillToggle = Activated
    .i1 = Inactive

# @k=1
n1 = {""}
    # @p=name @t=array
    .name = Magic Storage Bag
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = A portable magical tool that allows you to carry⎵
    .description-i1 = far more items than usual. However,⎵
    .description-i2 = even magical tools have their storage limits..
    # @p=ability @t=array
    .ability = Weapon capacity: {"${QJ.MPMZ.tl.ex_playerCheckInventory('weapon')}"}
    .ability-i1 = Gear capacity: {"${QJ.MPMZ.tl.ex_playerCheckInventory('gear')}"}

# @k=2
n2 = {""}
    # @p=name @t=array
    .name = Senpo
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = A quick step on the ground covers a short distance,
    .description-i1 = allowing you to dodge some attacks. It’s merely a starting dash⎵
    .description-i2 = technique, but the user insists on giving it a cool name
    # @p=ability @t=array
    .ability = Hold Space Bar to activate

# @k=3
n3 = {""}
    # @p=name @t=array
    .name = Senpo Tachi
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = A sword-drawing technique learned from the young Sword Master.
    .description-i1 = By combining with SenPo, you unleash a speed-enhanced ⎵
    .description-i2 = strike — enough to knock enemies away if timed right.
    # @p=ability @t=array
    .ability = Left Click during Senpo: Slash, damage scales with speed
    .ability-i1 = Hold Right Click during Senpo: Charge, effects scale with momentum
    # @p=mobileAbility @t=array
    .mobileAbility = Tap the skill button to slash, damage scales with movement speed
    .mobileAbility-i1 = Hold the skill button to charge, effect scales with momentum

# @k=4
n4 = {""}
    # @p=name @t=array
    .name = Whirlwind Slash
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = Spin while swinging your weapon to launch continuous attacks.⎵
    .description-i1 = The attack speed increases over time. For those who aren't great⎵
    .description-i2 = with sword techniques, this move is easy to learn and effective.
    # @p=ability @t=array
    .ability = Hold Right Click to activate the skill
    .ability-i1 = Cancel during spinning to throw your weapon
    # @p=mobileAbility @t=array
    .mobileAbility = Hold the skill button to activate the skill
    .mobileAbility-i1 = Cancel while spinning to throw your weapon

# @k=6
n6 = {""}
    # @p=name @t=array
    .name = Lucky Pervert
    # @p=subtitle @t=array
    .subtitle = true
    # @p=description @t=array
    .description = A legendary perverted constitution that activates on its own,⎵
    .description-i1 = even without the user realizing it.
    .description-i2 = As if blessed and guided by an unseen goddess, irresistible forces⎵
    .description-i3 = push you into blush-inducing, heart-pounding fanservice scenarios…!
    # @p=ability @t=array
    .ability = Always creates the perfect opportunities to trigger lewd events!

# @k=7
n7 = {""}
    # @p=name @t=array
    .name = Danger Sense
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = Often called ‘Mind's Eye’, but it's actually a sense⎵
    .description-i1 = sharpened by countless brushes with death.
    .description-i2 = In other words, more like a trauma reflex than an actual skill...
    # @p=ability @t=array
    .ability = Hover the mouse over the target to view detailed info
    # @p=mobileAbility @t=array
    .mobileAbility = Tap the target to view detailed info

# @k=10
n10 = {""}
    # @p=name @t=array
    .name = Breath Concealment
    # @p=subtitle @t=array
    .subtitle = true
    # @p=description @t=array
    .description = A ninja technique. I only picked it up in a rush, but…
    .description-i1 = somehow, I got the hang of it pretty quickly.
    # @p=ability @t=array
    .ability = Press Shift while active to enter stealth
    .ability-i1 = Reduces the monster's detection range by \c[17]{"${1+$gameParty.leader().skillMasteryLevel(10)}"}\c[108] tile
    .ability-i2 = Reduces \str[120]’s alert increase rate during peeking by \c[17]{"${15+15*$gameParty.leader().skillMasteryLevel(10)}"}%\c[0]

# @k=11
n11 = {""}
    # @p=name @t=array
    .name = Backstab
    # @p=subtitle @t=array
    .subtitle = true
    # @p=description @t=array
    .description = A ninja technique. Can be activated while in stealth
    .description-i1 = Strike an unguarded enemy from behind for massive damage!
    # @p=ability @t=array
    .ability = Skill Proficiency: \c[6]{"${$gameActors.actor(1).skillMasteryUses(11)}"}\c[0]
    .ability-i1 = Assassination Damage Bonus: \c[17]{"${Math.round(200 + (2333 - 200) * Math.pow($gameActors.actor(1).skillMasteryLevel(11) / 9, 1.8))}"}%\c[0]

# @k=12
n12 = {""}
    # @p=name @t=array
    .name = Musou Burst Stream
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = A secret finisher inherited from ASABA, who embraced sorrow
    .description-i1 = In an instant too fast for the eye to see, a hundred strikes land—
    .description-i2 = leaving the enemy with nothing but final darkness!
    # @p=ability @t=array
    .ability = Skill command:  {"{"}⬆⬇⬅⮕⬆⬇{"}"}
    .ability-i1 = Each use of the skill consumes some HP

# @k=15
n15 = {""}
    # @p=name @t=array
    .name = Crossdressing
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = You put on clothes not meant for you… and something inside you⎵
    .description-i1 = stirred. No combat bonus—might even mess with your head a little.
    .description-i2 = Your companions glance oddly, and enemies might pause… maybe.
    .description-i3 = After all, in this world—cuteness is justice!
    # @p=ability @t=array
    .ability = Increases Sin based on the number of crossdressing items equipped!

# @k=16
n16 = {""}
    # @p=name @t=array
    .name = Bladekeepers
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = "No matter how you swing your weapons!" "We’ll rise to call you out!"
    .description-i1 = "To stop the blades from wearing away!" "To protect the dignity of arms!"
    .description-i2 = "For we believe the sword is master, and humans are but servants!"
    .description-i3 = "The most absurd yet unshakable believers!"
    .description-i4 = "We are—Weapon Preservationists—the Bladekeepers!"
    # @p=ability @t=array
    .ability = Wearing the badge makes you one of them now

# @k=18
n18 = {""}
    # @p=name @t=array
    .name = Weapon Break
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = All weapons have durability limits,⎵
    .description-i1 = and since the user isn’t good at precise attacks.
    .description-i2 = there’s a risk of breaking them. But when the weapon does break —
    .description-i3 = it’ll land a powerful critical hit!
    # @p=ability @t=array
    .ability = Final hit damage boost: \c[6]{"${200+(100*$gameActors.actor(1).skillMasteryLevel(48))}"}%\c[0]

# @k=26
n26 = {""}
    # @p=name @t=array
    .name = Swordsmanship Training
    # @p=subtitle @t=array
    .subtitle = true
    # @p=description @t=array
    .description = Sought advice from a swordmaster girl on how to get stronger
    .description-i1 = All she said was ‘Just swing your sword 1,000 times every day!’
    .description-i2 = —Will that really work!? Anyway, let’s give it a try...
    # @p=ability @t=array
    .ability = Practice Swings Completed: {"{"}\c[6]{"${QJ.MPMZ.tl.playerSwordsmanshipTraining(1)}"}\c[0]
    .ability-i1 = Base attack damage of melee weapons increased by \c[6]{"${QJ.MPMZ.tl.playerSwordsmanshipTraining(2)}"}%
