# Auto-generated by json_to_ftl.py

# @p=gameTitle @t=array
gameTitle = A Simple Life with My Unobtrusive Girl⎵

# @p=goldHeld @t=array
goldHeld = Gold

# @p=quantityHeld @t=array
quantityHeld = \fs[16]•Quantity Held:\c[17] {"${}"} \c[0]\py[-8]

# @p=autoUpdate @t=array
autoUpdate =
    Update available: Version {"${}"} game data detected.⎵
    Would you like to download and update now?

# @p=fullScreen @t=array
fullScreen = Full Screen

# @p=masterVolume @t=array
masterVolume = Master Volume

# @p=voiceVolume @t=array
voiceVolume = Voice Volume

# @p=BgmVolume @t=array
BgmVolume = BGM Volume

# @p=BgsVolume @t=array
BgsVolume = BGS Volume

# @p=SeVolume @t=array
SeVolume = SE Volume

# @p=MaxPlayerMsgs @t=array
MaxPlayerMsgs = Max Player Msgs

# @p=GameFAQ @t=array
GameFAQ = Game Guide

# @p=ShowWeaponDurability @t=array
ShowWeaponDurability = Show Weapon Durability

# @p=DisableAutoUpdate @t=array
DisableAutoUpdate = Disable Auto Update

# @p=LockedFPS @t=array
LockedFPS = Locked 60 FPS

# @p=Language @t=array
Language = Game Language

# @p=SwitchLanguage @t=array
SwitchLanguage =
    Game language change detected!
    Restarting now to apply the new language settings!

# @p=ErrorReport @t=array
ErrorReport =
    An error occurred. Please report the bug on the NLCH Discord server.
    (Click 'OK' to open the invite link)
    (Attach a screenshot of the error)

# @p=UpdateComplete1 @t=array
UpdateComplete1 =
    Game update completed!
    The game will restart automatically after closing this window.
    You can load the auto-save to resume progress!

# @p=UpdateComplete2 @t=array
UpdateComplete2 =
    Game update completed!
    The game will restart shortly to apply the update!

# @p=RemindToUpdate @t=array
RemindToUpdate =
    An error has occurred and the game is frozen.
    A newer patch is available—
    Please use auto-update to fix the issue!

# @p=bagFull @t=array
bagFull = Inventory limit exceeded!!

# @p=noStatusEffects @t=array
noStatusEffects = No status effects at all!

# @p=unimplementedDoor @t=array
unimplementedDoor = This door won't push open from this side

# @p=zipUpdateComplete @t=array
zipUpdateComplete =
    Patch installed successfully.⎵
    Restarting the game to apply the update!

# @p=zipUpdateFail @t=array
zipUpdateFail =
    Failed to extract and install the patch!
    Please try the auto-update again or
    manually extract the patch files to install!

# @p=fileDownloadedSuccessfully @t=array
fileDownloadedSuccessfully = {"${}"} downloaded successfully!

# @p=fileDownloadFailed @t=array
fileDownloadFailed = {"${}"} failed to download! Retrying now!

# @p=installPatch @t=array
installPatch = Patch requires extraction—installing now. This may cause the game to lag, please be patient!

# @p=totalFilesToUpdate @t=array
totalFilesToUpdate = Detected {"${}"} file(s) to update—starting download process!

# @p=silentUpdateSuccess @t=array
silentUpdateSuccess = New patch content for {"${}"} has been successfully installed and will take effect upon the next restart.

# @p=outdatedVersionWarning @t=array
outdatedVersionWarning =
    Your current game version is outdated. The latest version is {"${}"}.
    Major version updates do not support automatic updates.⎵
    Please re-download the game from the official source.

# @p=renameCharacter @t=array
renameCharacter =
    I remember now—
    she is...

# @p=heroName @t=array
heroName = Onii-chan

# @p=heroineName @t=array
heroineName = Imouto

# @p=nonHardwareAccelerated @t=array
nonHardwareAccelerated =
    The game is currently running on integrated graphics!
    If your PC has a dedicated GPU, we recommend setting Game.exe⎵
    to use it in your graphics control panel for a smoother gaming experience.

# @p=isAmdCPU @t=array
isAmdCPU =
    Your CPU is detected as an AMD processor.
    Some AMD chips may experience frame drops when playing VP9 (WebM) videos⎵
    in a Chromium environment. If you encounter this issue, try forcing the game to
    use GPU rendering or update your drivers to help alleviate the problem.

# @p=failedToLoad @t=array
failedToLoad =
    This kind of issue may be caused by:
    ① Game files corrupted or filenames garbled due to encoding issues during extraction/installation.
    ② The developer forgetting to include the file—please wait for a patch update to fix it.

# @p=LowResMode @t=array
LowResMode = Low Graphics Mode

# @p=lowResModeWarning @t=array
lowResModeWarning =
    This feature is mainly for performance optimization on Android devices and may have little effect on the PC version.
    When enabled, the game renders maps and images at a lower resolution and then scales them up,⎵
    reducing GPU load on mobile devices and lowering heat generation and power consumption.
    Note: This is an experimental feature, and its effectiveness may vary depending on the device.
    You can disable this feature at any time to immediately restore full image clarity.

# @p=cloudSaveServiceWarning @t=array
cloudSaveServiceWarning =
    As the cloud save database is still under construction,
    this feature will temporarily request access to your Google Drive
    in order to store game save files in the NLCH/save folder.
    Uploaded save files will only be used for future synchronization and⎵
    downloading back into the game, and will not be used for any other purposes.
    Do you agree to grant the game permission to access your Google Drive?

# @p=uploadSaveFile @t=array
uploadSaveFile =
    Downloading a save file from Google Drive will overwrite your current local save data!
    Do you want to continue?

# @p=nearbyMonstersCount @t=array
nearbyMonstersCount = Detected nearby monsters

# @p=nearbyTreasuresCount @t=array
nearbyTreasuresCount = Detected nearby treasures

# @p=underwaterTreasuresCount @t=array
underwaterTreasuresCount = Detected underwater treasures

# @p=steamWishlist @t=array
steamWishlist =
    Our Steam store page is finally live!
    Please add us to your wishlist and support us! (*´∀`)~♥
    ⬇Click below to open the Steam page.

# @p=memberMenu|firstTimeNotice @t=array
memberMenu--firstTimeNotice =
    This ownership verification feature is currently experimental.
    You can sign in with Patreon here,⎵
    or link your Itch account for ownership verification.
    If you have an active subscription,⎵
    or already own the game on Itch,
    you can use features such as major update auto-patching.
    
    Please note:
    At this time, verification is only available for players⎵
    who bought the game on Itch or Patreon,⎵
    or players with a paid Patreon subscription.

# @p=memberMenu|shortHint @t=str
memberMenu--shortHint = ⎵Can now enable cloud saves & major updates

# @p=memberMenu|waitingLogin @t=str
memberMenu--waitingLogin = Waiting for login completion...

# @p=memberMenu|notLoggedIn @t=str
memberMenu--notLoggedIn = Not Logged In

# @p=memberMenu|RequestingLogin @t=str
memberMenu--RequestingLogin = Requesting login link...

# @p=memberMenu|openingWindow @t=str
memberMenu--openingWindow = Opening Patreon login window...

# @p=memberMenu|cloudSave @t=str
memberMenu--cloudSave = Use Cloud Save

# @p=memberMenu|logInFirst @t=str
memberMenu--logInFirst = Please click this button to log in first

# @p=memberMenu|CheckUpdates @t=str
memberMenu--CheckUpdates = Update to Latest Version

# @p=memberMenu|Subscribed @t=str
memberMenu--Subscribed = Subscription confirmed!

# @p=memberMenu|subscribedAndItchUser @t=str
memberMenu--subscribedAndItchUser = Subscription confirmed! (Itch ownership verified)

# @p=memberMenu|NotSubscribed @t=str
memberMenu--NotSubscribed = No active subscription detected. Some features are unavailable.

# @p=memberMenu|lastCheck @t=str
memberMenu--lastCheck = LastCheck:⎵

# @p=memberMenu|checkLatestVersion @t=str
memberMenu--checkLatestVersion = Checking for the latest version, please wait...

# @p=memberMenu|isLatestVersion @t=str
memberMenu--isLatestVersion = You are already on the latest version!

# @p=memberMenu|notSponsor @t=str
memberMenu--notSponsor = Unverified users must subscribe first!

# @p=memberMenu|ImoutoFavorite @t=str
memberMenu--ImoutoFavorite = Imouto's Favorite

# @p=memberMenu|itchUser @t=str
memberMenu--itchUser = Itch user confirmed!

# @p=memberMenu|nonItchUser @t=str
memberMenu--nonItchUser = This game was not found in your Itch library!

# @p=memberMenu|itchVerifyNotice @t=str
memberMenu--itchVerifyNotice = You can verify ownership of the Itch version here

# @p=memberMenu|itchVerifyAlert @t=str
memberMenu--itchVerifyAlert = Please log in before checking the Itch version!

# @p=memberMenu|majorUpdateFailed @t=array
memberMenu--majorUpdateFailed =
    Major version update failed!
    Error code: {"${}"}
    Please try logging in for verification and start the update again,
    or send this screenshot to our Discord server for assistance!

# @p=AdventurersPathway|mapName @t=str
AdventurersPathway--mapName = ⎵-Adventurer's Pathway-⎵

# @p=ShallowRuinsLabyrinth|mapName @t=str
ShallowRuinsLabyrinth--mapName = ⎵-Shallow Ruins Labyrinth-⎵

# @p=ShallowRuinsLabyrinth|mapDescription @t=str
ShallowRuinsLabyrinth--mapDescription = ⎵A vast labyrinth filled with countless mysteries⎵

# @p=ForgottenCatacombe|mapName @t=str
ForgottenCatacombe--mapName = ⎵-Forgotten Catacombe-⎵

# @p=ForestofRuins|mapName @t=str
ForestofRuins--mapName = ⎵-Forest of Ruins-⎵

# @p=AbandonedForest|mapName @t=str
AbandonedForest--mapName = ⎵-Abandoned Forest-⎵

# @p=ExcavationSite|mapName @t=str
ExcavationSite--mapName = ⎵-Excavation Site-⎵

# @p=TheFallenChurch|mapName @t=str
TheFallenChurch--mapName = ⎵-The Fallen Church-⎵

# @p=DoorofStar|mapName @t=str
DoorofStar--mapName = ⎵-Door of Star-⎵

# @p=ScorchingLavaZone|mapName @t=str
ScorchingLavaZone--mapName = ⎵-Scorching Lava Zone-⎵

# @p=ScorchingLavaZone|mapDescription @t=str
ScorchingLavaZone--mapDescription = ⎵A blazing land woven in fire, where trials burn eternal⎵

# @p=Nibelungen|mapName @t=str
Nibelungen--mapName = ⎵-Nibelungen-⎵
