# Auto-generated by json_to_ftl.py

# @k=gameTitle
gameTitle = A Simple Life with My Unobtrusive Girl⎵

# @k=goldHeld
goldHeld = Gold

# @k=quantityHeld
quantityHeld = \fs[16]•Quantity Held:\c[17] ${} \c[0]\py[-8]

# @k=autoUpdate
autoUpdate = Update available: Version ${} game data detected.⎵
    .i1 = Would you like to download and update now?

# @k=fullScreen
fullScreen = Full Screen

# @k=masterVolume
masterVolume = Master Volume

# @k=voiceVolume
voiceVolume = Voice Volume

# @k=BgmVolume
BgmVolume = BGM Volume

# @k=BgsVolume
BgsVolume = BGS Volume

# @k=SeVolume
SeVolume = SE Volume

# @k=MaxPlayerMsgs
MaxPlayerMsgs = Max Player Msgs

# @k=GameFAQ
GameFAQ = Game Guide

# @k=ShowWeaponDurability
ShowWeaponDurability = Show Weapon Durability

# @k=DisableAutoUpdate
DisableAutoUpdate = Disable Auto Update

# @k=LockedFPS
LockedFPS = Locked 60 FPS

# @k=Language
Language = Game Language

# @k=SwitchLanguage
SwitchLanguage = Game language change detected!
    .i1 = Restarting now to apply the new language settings!

# @k=ErrorReport
ErrorReport = An error occurred. Please report the bug on the NLCH Discord server.
    .i1 = (Click 'OK' to open the invite link)
    .i2 = (Attach a screenshot of the error)

# @k=UpdateComplete1
UpdateComplete1 = Game update completed!
    .i1 = The game will restart automatically after closing this window.
    .i2 = You can load the auto-save to resume progress!

# @k=UpdateComplete2
UpdateComplete2 = Game update completed!
    .i1 = The game will restart shortly to apply the update!

# @k=RemindToUpdate
RemindToUpdate = An error has occurred and the game is frozen.
    .i1 = A newer patch is available—
    .i2 = Please use auto-update to fix the issue!

# @k=bagFull
bagFull = Inventory limit exceeded!!

# @k=noStatusEffects
noStatusEffects = No status effects at all!

# @k=unimplementedDoor
unimplementedDoor = This door won't push open from this side

# @k=zipUpdateComplete
zipUpdateComplete = Patch installed successfully.⎵
    .i1 = Restarting the game to apply the update!

# @k=zipUpdateFail
zipUpdateFail = Failed to extract and install the patch!
    .i1 = Please try the auto-update again or
    .i2 = manually extract the patch files to install!

# @k=fileDownloadedSuccessfully
fileDownloadedSuccessfully = ${} downloaded successfully!

# @k=fileDownloadFailed
fileDownloadFailed = ${} failed to download! Retrying now!

# @k=installPatch
installPatch = Patch requires extraction—installing now. This may cause the game to lag, please be patient!

# @k=totalFilesToUpdate
totalFilesToUpdate = Detected ${} file(s) to update—starting download process!

# @k=silentUpdateSuccess
silentUpdateSuccess = New patch content for ${} has been successfully installed and will take effect upon the next restart.

# @k=outdatedVersionWarning
outdatedVersionWarning = Your current game version is outdated. The latest version is ${}.
    .i1 = Major version updates do not support automatic updates.⎵
    .i2 = Please re-download the game from the official source.

# @k=renameCharacter
renameCharacter = I remember now—
    .i1 = she is...

# @k=heroName
heroName = Onii-chan

# @k=heroineName
heroineName = Imouto

# @k=nonHardwareAccelerated
nonHardwareAccelerated = The game is currently running on integrated graphics!
    .i1 = If your PC has a dedicated GPU, we recommend setting Game.exe⎵
    .i2 = to use it in your graphics control panel for a smoother gaming experience.

# @k=isAmdCPU
isAmdCPU = Your CPU is detected as an AMD processor.
    .i1 = Some AMD chips may experience frame drops when playing VP9 (WebM) videos⎵
    .i2 = in a Chromium environment. If you encounter this issue, try forcing the game to
    .i3 = use GPU rendering or update your drivers to help alleviate the problem.

# @k=failedToLoad
failedToLoad = This kind of issue may be caused by:
    .i1 = ① Game files corrupted or filenames garbled due to encoding issues during extraction/installation.
    .i2 = ② The developer forgetting to include the file—please wait for a patch update to fix it.

# @k=LowResMode
LowResMode = Low Graphics Mode

# @k=lowResModeWarning
lowResModeWarning = This feature is mainly for performance optimization on Android devices and may have little effect on the PC version.
    .i1 = When enabled, the game renders maps and images at a lower resolution and then scales them up,⎵
    .i2 = reducing GPU load on mobile devices and lowering heat generation and power consumption.
    .i3 = Note: This is an experimental feature, and its effectiveness may vary depending on the device.
    .i4 = You can disable this feature at any time to immediately restore full image clarity.

# @k=cloudSaveServiceWarning
cloudSaveServiceWarning = As the cloud save database is still under construction,
    .i1 = this feature will temporarily request access to your Google Drive
    .i2 = in order to store game save files in the NLCH/save folder.
    .i3 = Uploaded save files will only be used for future synchronization and⎵
    .i4 = downloading back into the game, and will not be used for any other purposes.
    .i5 = Do you agree to grant the game permission to access your Google Drive?

# @k=uploadSaveFile
uploadSaveFile = Downloading a save file from Google Drive will overwrite your current local save data!
    .i1 = Do you want to continue?

# @k=nearbyMonstersCount
nearbyMonstersCount = Detected nearby monsters

# @k=nearbyTreasuresCount
nearbyTreasuresCount = Detected nearby treasures

# @k=underwaterTreasuresCount
underwaterTreasuresCount = Detected underwater treasures

# @k=steamWishlist
steamWishlist = Our Steam store page is finally live!
    .i1 = Please add us to your wishlist and support us! (*´∀`)~♥
    .i2 = ⬇Click below to open the Steam page.

# @k=memberMenu
memberMenu = {""}
    # @p=firstTimeNotice @t=array
    .firstTimeNotice = This ownership verification feature is currently experimental.
    .firstTimeNotice-i1 = You can sign in with Patreon here,⎵
    .firstTimeNotice-i2 = or link your Itch account for ownership verification.
    .firstTimeNotice-i3 = If you have an active subscription,⎵
    .firstTimeNotice-i4 = or already own the game on Itch,
    .firstTimeNotice-i5 = you can use features such as major update auto-patching.
    .firstTimeNotice-i6 = 
    .firstTimeNotice-i7 = Please note:
    .firstTimeNotice-i8 = At this time, verification is only available for players⎵
    .firstTimeNotice-i9 = who bought the game on Itch or Patreon,⎵
    .firstTimeNotice-i10 = or players with a paid Patreon subscription.
    # @p=shortHint @t=str
    .shortHint = ⎵Can now enable cloud saves & major updates
    # @p=waitingLogin @t=str
    .waitingLogin = Waiting for login completion...
    # @p=notLoggedIn @t=str
    .notLoggedIn = Not Logged In
    # @p=RequestingLogin @t=str
    .RequestingLogin = Requesting login link...
    # @p=openingWindow @t=str
    .openingWindow = Opening Patreon login window...
    # @p=cloudSave @t=str
    .cloudSave = Use Cloud Save
    # @p=logInFirst @t=str
    .logInFirst = Please click this button to log in first
    # @p=CheckUpdates @t=str
    .CheckUpdates = Update to Latest Version
    # @p=Subscribed @t=str
    .Subscribed = Subscription confirmed!
    # @p=subscribedAndItchUser @t=str
    .subscribedAndItchUser = Subscription confirmed! (Itch ownership verified)
    # @p=NotSubscribed @t=str
    .NotSubscribed = No active subscription detected. Some features are unavailable.
    # @p=lastCheck @t=str
    .lastCheck = LastCheck:⎵
    # @p=checkLatestVersion @t=str
    .checkLatestVersion = Checking for the latest version, please wait...
    # @p=isLatestVersion @t=str
    .isLatestVersion = You are already on the latest version!
    # @p=notSponsor @t=str
    .notSponsor = Unverified users must subscribe first!
    # @p=ImoutoFavorite @t=str
    .ImoutoFavorite = Imouto's Favorite
    # @p=itchUser @t=str
    .itchUser = Itch user confirmed!
    # @p=nonItchUser @t=str
    .nonItchUser = This game was not found in your Itch library!
    # @p=itchVerifyNotice @t=str
    .itchVerifyNotice = You can verify ownership of the Itch version here
    # @p=itchVerifyAlert @t=str
    .itchVerifyAlert = Please log in before checking the Itch version!
    # @p=majorUpdateFailed @t=array
    .majorUpdateFailed = Major version update failed!
    .majorUpdateFailed-i1 = Error code: ${}
    .majorUpdateFailed-i2 = Please try logging in for verification and start the update again,
    .majorUpdateFailed-i3 = or send this screenshot to our Discord server for assistance!

# @k=AdventurersPathway
AdventurersPathway = {""}
    # @p=mapName @t=str
    .mapName = ⎵-Adventurer's Pathway-⎵

# @k=ShallowRuinsLabyrinth
ShallowRuinsLabyrinth = {""}
    # @p=mapName @t=str
    .mapName = ⎵-Shallow Ruins Labyrinth-⎵
    # @p=mapDescription @t=str
    .mapDescription = ⎵A vast labyrinth filled with countless mysteries⎵

# @k=ForgottenCatacombe
ForgottenCatacombe = {""}
    # @p=mapName @t=str
    .mapName = ⎵-Forgotten Catacombe-⎵

# @k=ForestofRuins
ForestofRuins = {""}
    # @p=mapName @t=str
    .mapName = ⎵-Forest of Ruins-⎵

# @k=AbandonedForest
AbandonedForest = {""}
    # @p=mapName @t=str
    .mapName = ⎵-Abandoned Forest-⎵

# @k=ExcavationSite
ExcavationSite = {""}
    # @p=mapName @t=str
    .mapName = ⎵-Excavation Site-⎵

# @k=TheFallenChurch
TheFallenChurch = {""}
    # @p=mapName @t=str
    .mapName = ⎵-The Fallen Church-⎵

# @k=DoorofStar
DoorofStar = {""}
    # @p=mapName @t=str
    .mapName = ⎵-Door of Star-⎵

# @k=ScorchingLavaZone
ScorchingLavaZone = {""}
    # @p=mapName @t=str
    .mapName = ⎵-Scorching Lava Zone-⎵
    # @p=mapDescription @t=str
    .mapDescription = ⎵A blazing land woven in fire, where trials burn eternal⎵

# @k=Nibelungen
Nibelungen = {""}
    # @p=mapName @t=str
    .mapName = ⎵-Nibelungen-⎵
