# Auto-generated by json_to_ftl.py

## n1
# @p=1|name @t=array
n1--name = Bigorna

# @p=1|subtitle @t=str
n1--subtitle = [empty string]

# @p=1|description @t=array
n1--description =
    Uma pesada bigorna da oficina de um ferreiro, carregada⎵
    como equipamento. Sua dureza e peso a tornam perfeita para
    afiar armas, embora possa ser difícil de manejar para os novatos...

# @p=1|ability @t=array
n1--ability =
    Senpo muda para puxar a bigorna e reparar armas
    Não repara armas mágicas ou de qualidade dourada

## n2
# @p=2|name @t=array
n2--name = Arma Joalhada

# @p=2|subtitle @t=str
n2--subtitle = {""}

# @p=2|description @t=array
n2--description =
    Minerais adormecidos no subsolo são bons meios alquímicos
    Dispositivo de magitecnologia em forma de adaga canaliza o poder de⎵
    gemas preciosas, mas foi abandonada devido ao alto custo…

# @p=2|ability @t=array
n2--ability =
    Consome uma gema aleatória ao atacar para carregar e aumentar o dano
    Quanto mais preciosa a gema, maior o dano mágico adicional

## n3
# @p=3|name @t=array
n3--name = Acessório de Cabelo Ímpar

# @p=3|subtitle @t=str
n3--subtitle = {""}

# @p=3|description @t=array
n3--description =
    Um acessório de cabelo adornado com um ornamento incomum
    É uma coelha… ou uma garota fantasiada de…?

# @p=3|ability @t=array
n3--ability = {""}

## n5
# @p=5|name @t=array
n5--name = Luvas de Proteção

# @p=5|subtitle @t=str
n5--subtitle = {""}

# @p=5|description @t=array
n5--description =
    Luvas de proteção feitas de materiais isolantes, originalmente⎵
    usadas por trabalhadores como EPI, Surpreendentemente,⎵
    elas também oferecem forte resistência contra ataques mágicos...

# @p=5|ability @t=array
n5--ability = Reduz consideravelmente o efeito de raios quando equipado

## n6
# @p=6|name @t=array
n6--name = Nascimento da Infortuna

# @p=6|subtitle @t=str
n6--subtitle = {""}

# @p=6|description @t=array
n6--description =
    Parasitada por uma Pedra Filosofal, uma fraca criatura foi
    imbuída de vitalidade infinita, presa em um ciclo interminável
    até que a loucura tomou conta. Mesmo removida, esse poder permanece

# @p=6|ability @t=array
n6--ability =
    Aumenta o PV. Aumenta os efeitos de recuperação de PV em 25%
    Concede regeneração automática quando equipado

## n7
# @p=7|name @t=array
n7--name = Feto Amaldiçoado

# @p=7|subtitle @t=str
n7--subtitle = {""}

# @p=7|description @t=array
n7--description =
    Um feto amaldiçoado que, apesar de tudo,
    permanece vivo.Sua intensa vontade de sobreviver e transbordar
    vitalidade pode até mesmo influenciar seu portador

# @p=7|ability @t=array
n7--ability = Aumenta o PV. Aumenta os efeitos de recuperação de PV em 20%

## n8
# @p=8|name @t=array
n8--name = Aglomerado de Cristais de Mana

# @p=8|subtitle @t=str
n8--subtitle = {""}

# @p=8|description @t=array
n8--description =
    Um mineral moldado pelo Grande Labirinto, contendo traços de mana
    Carregá-lo aprimora a compreensão mágica

# @p=8|ability @t=array
n8--ability =
    Equipá-lo aumenta a velocidade de conjuração e o poder mágico
    Os ataques de armas mágicas causam 5% de dano mágico adicional

## n9
# @p=9|name @t=array
n9--name = Aglomerado Abissal de Mana

# @p=9|subtitle @t=str
n9--subtitle = {""}

# @p=9|description @t=array
n9--description =
    Um raro aglomerado infundido com mana densa,
    irradiando ondas mágicas. Altamente cobiçado por alquimistas

# @p=9|ability @t=array
n9--ability =
    Ao equipá-lo, aumenta a velocidade de conjuração e o poder mágico
    Os ataques de armas mágicas causam 10% de dano mágico adicional

## n10
# @p=10|name @t=array
n10--name = Tiara do Foco

# @p=10|subtitle @t=str
n10--subtitle = {""}

# @p=10|description @t=array
n10--description =
    Uma tiara usada pelo grande sábio em sua juventude como
    aventureiro. Foca a mente e repele distrações externas

# @p=10|ability @t=array
n10--ability =
    Imune a Atordoamento
    Aprimora o poder mágico e a escala de conjuração

## n11
# @p=11|name @t=array
n11--name = Luvas Drenadoras de Mana

# @p=11|subtitle @t=str
n11--subtitle = {""}

# @p=11|description @t=array
n11--description =
    Luvas usadas pelo grande sábio em sua juventude como
    aventureiro. Elas reúnem mana naturalmente,
    imbuindo as armas com propriedades mágicas

# @p=11|ability @t=array
n11--ability =
    Quando equipado, a arma empunhada se transforma em uma arma mágica
    Os ataques de armas mágicas causam 30% de dano mágico adicional

## n12
# @p=12|name @t=array
n12--name = Garras de Neko Emprestadas

# @p=12|subtitle @t=array
n12--subtitle = ⎵“…Miau~?”

# @p=12|description @t=array
n12--description =
    Garras de Neko escondidas dentro de um Slime Neko, aparentemente imbuídas
    com o espírito de um gato. Ao equipá-las, aumentam sua agilidade!

# @p=12|ability @t=array
n12--ability = Aumenta o poder de ataque e a velocidade de ataque

## n13
# @p=13|name @t=array
n13--name = Garras de Neko Emprestadas

# @p=13|subtitle @t=array
n13--subtitle = ⎵“…Miau~?”

# @p=13|description @t=array
n13--description =
    Patinhas de Neko escondidas dentro de um Slime Neko, aparentemente imbuídas
    com o espírito de um gato. Ao equipá-las, aumentam sua agilidade!

# @p=13|ability @t=array
n13--ability = Aumenta a velocidade de ataque e de movimento, reduz a recarga de Senpo

## n14
# @p=14|name @t=array
n14--name = Anel da Relva Fragrante

# @p=14|subtitle @t=str
n14--subtitle = {""}

# @p=14|description @t=array
n14--description =
    Forjado de folhas e rizomas entrelaçados, este anel libera um suave perfume herbal
    Antes usado como talismã por viajantes, tornou-se um símbolo de vitalidade e energia

# @p=14|ability @t=array
n14--ability =
    PV Máx. +\c[29]{"${QJ.MPMZ.tl.ex_fragrantGrassRingEffectResolve()}"}\c[0]
    Usar múltiplas peças deste equipamento aprimora seu efeito

## n15
# @p=15|name @t=array
n15--name = Traje de Pelúcia de Neko

# @p=15|subtitle @t=str
n15--subtitle = {""}

# @p=15|description @t=array
n15--description =
    Um traje de pelúcia de gato aconchegante — felpudo e super grande
    Seu design espaçoso envolve você e até esconde alguns extras~

# @p=15|ability @t=array
n15--ability =
    Aumenta a capacidade de transportar armas em +10
    Aumenta a capacidade de transportar equipamentos em +20

## n16
# @p=16|name @t=array
n16--name = Elmo de Espinhos Perfurantes

# @p=16|subtitle @t=str
n16--subtitle = {""}

# @p=16|description @t=array
n16--description =
    Uma armadura metálica cravejada de espinhos em todos os ângulos,
    oferecendo defesa sólida e causando automaticamente dano a inimigos próximos

# @p=16|ability @t=array
n16--ability = Causa dano automaticamente a inimigos próximos

## n17
# @p=17|name @t=array
n17--name = Armadura de Espinhos Perfurantes

# @p=17|subtitle @t=str
n17--subtitle = {""}

# @p=17|description @t=array
n17--description =
    Uma armadura metálica cravejada de espinhos em todos os ângulos,
    oferecendo defesa sólida e causando automaticamente dano a inimigos próximos

# @p=17|ability @t=array
n17--ability = Causa dano automaticamente a inimigos próximos

## n18
# @p=18|name @t=array
n18--name = Manoplas de Espinhos Perfurantes

# @p=18|subtitle @t=str
n18--subtitle = {""}

# @p=18|description @t=array
n18--description =
    Uma armadura metálica cravejada de espinhos em todos os ângulos,
    oferecendo defesa sólida e causando automaticamente dano a inimigos próximos

# @p=18|ability @t=array
n18--ability = Causa dano automaticamente a inimigos próximos ao atacar

## n19
# @p=19|name @t=array
n19--name = Botas de Espinhos Perfurantes

# @p=19|subtitle @t=str
n19--subtitle = {""}

# @p=19|description @t=array
n19--description =
    Uma armadura metálica cravejada de espinhos em todos os ângulos,
    oferecendo defesa sólida e causando automaticamente dano a inimigos próximos

# @p=19|ability @t=array
n19--ability = Causa dano automaticamente a inimigos próximos ao se mover

## n20
# @p=20|name @t=array
n20--name = Elmo do Cavaleiro

# @p=20|subtitle @t=str
n20--subtitle = {""}

# @p=20|description @t=array
n20--description =
    A armadura padrão dos cavaleiros da corte. Seu design ornamentado e robusto
    simboliza a adesão deles ao código da cavalaria

# @p=20|ability @t=array
n20--ability = Aumenta a defesa quando o PV está abaixo de \c[10]30%\c[0]

## n21
# @p=21|name @t=array
n21--name = Armadura do Cavaleiro

# @p=21|subtitle @t=str
n21--subtitle = {""}

# @p=21|description @t=array
n21--description =
    A armadura padrão dos cavaleiros da corte. Seu design ornamentado e robusto
    simboliza a adesão deles ao código da cavalaria

# @p=21|ability @t=array
n21--ability = Aumenta a defesa quando o PV está abaixo de \c[10]30%\c[0]

## n22
# @p=22|name @t=array
n22--name = Manoplas do Cavaleiro

# @p=22|subtitle @t=str
n22--subtitle = {""}

# @p=22|description @t=array
n22--description =
    A armadura padrão dos cavaleiros da corte. Seu design ornamentado e robusto
    Simboliza a adesão deles ao código da cavalaria

# @p=22|ability @t=array
n22--ability = Aumenta o ataque e a defesa quando o PV está abaixo de \c[10]30%\c[0]

## n23
# @p=23|name @t=array
n23--name = Caneleiras do Cavaleiro

# @p=23|subtitle @t=str
n23--subtitle = {""}

# @p=23|description @t=array
n23--description =
    A armadura padrão dos cavaleiros da corte. Seu design ornamentado e robusto
    simboliza a adesão deles ao código da cavalaria

# @p=23|ability @t=array
n23--ability = Aumenta a velocidade de movimento quando o PV está abaixo de \c[10]30%\c[0]

## n24
# @p=24|name @t=array
n24--name = Traje do Caçador

# @p=24|subtitle @t=str
n24--subtitle = {""}

# @p=24|description @t=array
n24--description =
    Feito de couro grosso e linho resistente, já foi o traje cotidiano⎵
    dos caçadores da floresta. Defesa limitada, mas leve e flexível⎵
    Ideal para se mover rapidamente pela floresta

# @p=24|ability @t=array
n24--ability = Regenera lentamente o HP ao permanecer em terreno gramado

## n25
# @p=25|name @t=array
n25--name = Cinto do Caçador

# @p=25|subtitle @t=str
n25--subtitle = {""}

# @p=25|description @t=array
n25--description =
    Confeccionado em couro resistente, com fivelas e bolsas duráveis
    um dia essencial para os caçadores da floresta em suas jornadas,⎵
    continua leve e não sobrecarrega mesmo durante longas caminhadas

# @p=25|ability @t=array
n25--ability =
    PV Máx +20, velocidade de movimento aumentada
    Capacidade extra de carga: armas +5, equipamentos +5

## n26
# @p=26|name @t=array
n26--name = Pena da Ave de Fogo

# @p=26|subtitle @t=array
n26--subtitle = {""}

# @p=26|description @t=array
n26--description =
    Uma pena da Ave de Fogo.
    símbolizando vida eterna, continua queimando com uma chama quente.
    Mesmo uma única pena guarda o poder de reviver os mortos.

# @p=26|ability @t=array
n26--ability =
    Ativa quando o PV chega a zero, restaurando totalmente o HP
    O item é destruído após a ativação

## n27
# @p=27|name @t=array
n27--name = Papel Higiênico

# @p=27|subtitle @t=str
n27--subtitle = {""}

# @p=27|description @t=array
n27--description =
    Um papel higiênico trazido de casa
    Um item útil para aventureiros que de repente precisam
    de uma pausa para ir ao banheiro em uma masmorra perigosa

# @p=27|ability @t=array
n27--ability = Reduz o dano de Sangramento recebido em \c[10]30%\c[0]

## n28
# @p=28|name @t=array
n28--name = Mão do demônio

# @p=28|subtitle @t=array
n28--subtitle = {""}

# @p=28|description @t=array
n28--description =
    Um braço maciço flamejante com a força bruta do clã dos demônios
    Simboliza uma potência tão feroz que pode facilmente esmagar pedra sólida
    Para humanos, é uma força muito difícil de controlar

# @p=28|ability @t=array
n28--ability =
    Poder de ataque físico +100%, velocidade de ataque diminui
    É provável

## n29
# @p=29|name @t=array
n29--name = Jack Atrevido

# @p=29|subtitle @t=array
n29--subtitle = “Este anseia por gritos...”

# @p=29|description @t=array
n29--description =
    Uma das armas letais de um infame assassino,
    Ainda tremendo em antecipação

# @p=29|ability @t=array
n29--ability = Causa mais dano a inimigos com menos PV, até \c[10]30%\c[0]

## n30
# @p=30|name @t=array
n30--name = Adaga do Caçador

# @p=30|subtitle @t=array
n30--subtitle = “Morte pelo cano, fortuna pela lâmina”

# @p=30|description @t=array
n30--description =
    Uma pequena e afiada adaga que cabe facilmente em uma bota
    Para um caçador, ela sempre extrai a última oferenda da presa

# @p=30|ability @t=array
n30--ability = Aumenta as chances de obter carne

## n31
# @p=31|name @t=array
n31--name = Fantasma da Noite Nebulosa

# @p=31|subtitle @t=array
n31--subtitle = “Este anseia por desaparecer...”

# @p=31|description @t=array
n31--description =
    Uma das ferramentas letais de um infame assassino,
    Projetada para ocultar sua presença

# @p=31|ability @t=array
n31--ability =
    Entra periodicamente em estado invisível
    Execuções enquanto invisível causam o dobro de dano

## n32
# @p=32|name @t=array
n32--name = Soco de Neko

# @p=32|subtitle @t=str
n32--subtitle = {""}

# @p=32|description @t=array
n32--description =
    "Hyaa! Não mexe comigo, miau!"
    Luvas de patinha de gato acolchoadas, a arma preciosa de uma certa catgirl
    Usá-las concede agilidade felina e uma vontade de comer peixe…

# @p=32|ability @t=array
n32--ability =
    Velocidade de ataque aumentada. +1 ataque extra por ataque
    A chance de ataques extras ativarem efeitos especiais é reduzida pela metade

## n33
# @p=33|name @t=array
n33--name = Capacete de Maçã

# @p=33|subtitle @t=str
n33--subtitle = {""}

# @p=33|description @t=array
n33--description =
    Um capacete feito de maçãs, então não dá para
    Esperar muita defesa. Mas as maçãs são tão deliciosas

# @p=33|ability @t=array
n33--ability = Há uma chance de ativar cura ao ser ferido

## n34
# @p=34|name @t=array
n34--name = Anel da Lâmina Afiada

# @p=34|subtitle @t=str
n34--subtitle = {""}

# @p=34|description @t=array
n34--description =
    Diz a lenda que um aventureiro, com medo de lutar de mãos vazias,⎵
    embutiu uma espada em um anel. Pequeno demais para⎵
    ser usada como arma, mas aumenta a presença de quem a carrega

# @p=34|ability @t=array
n34--ability = Poder de ataque físico +15%

## n35
# @p=35|name @t=array
n35--name = Wakizashi

# @p=35|subtitle @t=str
n35--subtitle = {""}

# @p=35|description @t=array
n35--description =
    Lâmina curta forjada com precisão, portada por samurais⎵
    estrangeiros como arma secundária. Causa cortes profundos
    e sangramento persistente

# @p=35|ability @t=array
n35--ability =
    Contagem de ataques normais com armas corpo a corpo +1
    O ataque extra tem chance de infligir Sangramento

## n36
# @p=36|name @t=array
n36--name = Neko da Sorte

# @p=36|subtitle @t=str
n36--subtitle = {""}

# @p=36|description @t=array
n36--description =
    Um pequeno Servo ganancioso, com um olhar eternamente insatisfeito
    Recolhe com entusiasmo todos os itens, sem se importar com o valor

# @p=36|ability @t=array
n36--ability =
    O Neko da Sorte coleta automaticamente todos os itens para você
    Ao equipar mais de um, apenas o alcance de coleta é ampliado

## n37
# @p=37|name @t=array
n37--name = ⎵Cofrinho

# @p=37|subtitle @t=str
n37--subtitle = {""}

# @p=37|description @t=array
n37--description =
    Um Servo fofinho que guarda o dinheiro coletado
    Algo pode acontecer quando estiver cheio, mas por enquanto, ele é apenas frágil

# @p=37|ability @t=array
n37--ability =
    Guarda o dinheiro com alegria. Poupança atual:\c[6]{"${$gameSelfVariables.value([1, 110, 'deposit'])}"}\c[0] ienes!
    Quebra facilmente quando atacado, perdendo todo o dinheiro armazenado

## n38
# @p=38|name @t=array
n38--name = ⎵Cofrinho Ganancioso

# @p=38|subtitle @t=str
n38--subtitle = {""}

# @p=38|description @t=array
n38--description =
    Um cofrinho cheio até a boca de riquezas — um sonho que virou realidade
    Ainda assim, mesmo com a barriga cheia de ouro, sua ganância não conhece limites

# @p=38|ability @t=array
n38--ability =
    Emite a aura da Demanda de Mamon. Poupança atual: \c[6]{"${$gameSelfVariables.value([1, 110, 'deposit'])}"}\c[0] iene!
    Acumula riquezas incessantemente, liberando juros a cada 10 segundos

## n39
# @p=39|name @t=array
n39--name = Casco de Tartaruga Verde

# @p=39|subtitle @t=str
n39--subtitle = {""}

# @p=39|description @t=array
n39--description =
    Uma carapaça de tartaruga dura e pesada
    Carregá-la em terra firme impossibilita levantar os pés…!

# @p=39|ability @t=array
n39--ability = Reduz a velocidade de movimento e aumenta a velocidade de nado

## n40
# @p=40|name @t=array
n40--name = Uniforme de Maid

# @p=40|subtitle @t=str
n40--subtitle = {""}

# @p=40|description @t=array
n40--description =
    Um troféu obtido após dar uma lição na travessa garota de
    Orelhas de coelho. Ainda carrega o cheiro de terra e cenouras

# @p=40|ability @t=array
n40--ability =
    Ao equipar, te disfarça como um monstro, mas não pode atacar
    Ao equipá-lo, você se torna o melhor amigo da Maid Bunny

## n41
# @p=41|name @t=array
n41--name = Orelhas de Coelhinha Moe

# @p=41|subtitle @t=str
n41--subtitle = {""}

# @p=41|description @t=array
n41--description =
    Um acessório de orelhas de coelho destacável
    Não importa quem use, vai ficar absolutamente adorável!

# @p=41|ability @t=array
n41--ability = Abençoado com sorte! É provável que itens sejam dropados!

## n42
# @p=42|name @t=array
n42--name = Alma do Demônio das Bombas

# @p=42|subtitle @t=array
n42--subtitle = "Explo————são!"

# @p=42|description @t=array
n42--description =
    Uma determinação que abandonou tudo, consumida pelo desejo de explodir
    Agora que a carrega, não vai almejar explosões ainda maiores?

# @p=42|ability @t=array
n42--ability =
    Pequena chance de causar uma explosão ao atacar ou ao ser atingido
    Reduz em 50% o dano de explosões sofrido pelo próprio usuário

## n43
# @p=43|name @t=array
n43--name = Insígnia dos Guardiões da Lâmina

# @p=43|subtitle @t=array
n43--subtitle =
    "Vocês, aventureiros, me dão nojo!
    Só empunham suas lâminas para matar, sem ligar para o sofrimento deles

# @p=43|description @t=array
n43--description = Uma insígnia de camaradas que defendem a preservação das armas

# @p=43|ability @t=array
n43--ability =
    Poder de ataque -20%, ataque máximo limitado a 200
    Reduz em 20% toda a perda de durabilidade das armas

## n44
# @p=44|name @t=array
n44--name = ◉▽◉

# @p=44|subtitle @t=array
n44--subtitle = "A Sacabambaspis já viu de tudo."

# @p=44|description @t=array
n44--description =
    Uma antiga e lendária Serva-mesmo sendo um peixe, ela não consegue nadar
    Tem uma pele resistente, seu movimento especial é o Jato de Canhão Ciclônico!

# @p=44|ability @t=array
n44--ability =
    Consegue levantar a tartaruga Saccabankame e arremessá-la como um ataque
    Se cair na água, não consegue mais sair...

## n45
# @p=45|name @t=array
n45--name = Abraço Venenoso

# @p=45|subtitle @t=array
n45--subtitle = "Esta adaga está carregada com um veneno mortal, sabia— (lambe"

# @p=45|description @t=array
n45--description = Uma adaga curta mágica e venenosa — mantenha distância

# @p=45|ability @t=array
n45--ability =
    Um Servo que orbita automaticamente ao seu redor
    Alta chance de envenenar ao contato

## n46
# @p=46|name @t=array
n46--name = Punho da Fúria

# @p=46|subtitle @t=array
n46--subtitle = "Mão esquerda bate pesado, mão direita bate ainda mais pesado."

# @p=46|description @t=array
n46--description =
    Um poderoso punho mágico
    Transbordando de uma fúria insondável, continua fechado em punho…

# @p=46|ability @t=array
n46--ability =
    Um Servo que orbita automaticamente ao seu redor
    Empurra para trás qualquer inimigo que tocar

## n47
# @p=47|name @t=array
n47--name = Mão Amaldiçoada de Xerise

# @p=47|subtitle @t=str
n47--subtitle = {""}

# @p=47|description @t=array
n47--description =
    Uma mão decepada imbuída de poder necromântico
    Mesmo sem um corpo, permanece agitada e agressiva

# @p=47|ability @t=array
n47--ability =
    Um Servo que orbita automaticamente ao seu redor
    Amaldiçoa qualquer alvo para o qual aponte o dedo do meio

## n48
# @p=48|name @t=array
n48--name = Contrato de Encadeamento de Feitiços

# @p=48|subtitle @t=array
n48--subtitle =
    "Quando a pessoa que você ama morre, você deve tirar a própria vida.
    Quando a pessoa que você ama morre, não há outro caminho."

# @p=48|description @t=array
n48--description = Para salvar seu familiar, um certo alquimista forjou este contrato…

# @p=48|ability @t=array
n48--ability =
    Vincule-se ao seu servo — qualquer dano que ele receber será seu
    Cada servo vinculado concede a você um efeito de cura

## n49
# @p=49|name @t=array
n49--name = Chifre vermelho

# @p=49|subtitle @t=array
n49--subtitle = "Você nunca parou!"

# @p=49|description @t=array
n49--description =
    Um chifre carmesim repleto de magia de Jackalope
    Se a magia pudesse ser fornecida infinitamente, continuará acelerando⎵
    Até que se tornou um cometa que atravessou o céu!

# @p=49|ability @t=array
n49--ability =
    Quando totalmente carregado, o Senpo não tem recuperação e se move mais rápido
    Quando a carga estiver esgotada, ela irá recarregar automaticamente

## n50
# @p=50|name @t=array
n50--name = Batata Frita

# @p=50|subtitle @t=str
n50--subtitle = {""}

# @p=50|description @t=array
n50--description =
    Frito na hora com um molho quente,
    Quente e saboroso. Cuidado com as gaivotas!

# @p=50|ability @t=array
n50--ability = Atrai gaivotas que roubam suas batatas fritas

## n52
# @p=52|name @t=array
n52--name = Presente de Shadowcrawler

# @p=52|subtitle @t=str
n52--subtitle = {""}

# @p=52|description @t=array
n52--description =
    Disse ser um símbolo das profundezas onde as sombras espreitem
    Segurando isso faz você se sentir como se algo fosse⎵
    Silenciosamente escrevendo atrás de você —

# @p=52|ability @t=array
n52--ability =
    Velocidade de movimento aumenta
    Conquiste a atenção de ├├├├├├-de.

## n53
# @p=53|name @t=array
n53--name = Anel de Osso do Enforcado

# @p=53|subtitle @t=str
n53--subtitle = {""}

# @p=53|description @t=array
n53--description =
    Um anel feito com os ossos do falecido Enforcado
    Embora a maior parte de seu poder tenha se perdido,
    ainda concede ao portador um pouco de liberdade da gravidade

# @p=53|ability @t=array
n53--ability = Reduz o dano de queda em 50%

## n54
# @p=54|name @t=array
n54--name = Cálice Dourado Incompleto

# @p=54|subtitle @t=str
n54--subtitle = {""}

# @p=54|description @t=array
n54--description =
    Uma relíquia de santo ainda não preenchida, que abençoa
    Imensa sorte. A origem dessa bênção permanece desconhecida,
    Enquanto aguarda silenciosamente o dia em que será completada

# @p=54|ability @t=array
n54--ability = Aumenta grandemente a sorte. Dobra o dinheiro obtido

## n55
# @p=55|name @t=array
n55--name = Luvas do Incendiário

# @p=55|subtitle @t=array
n55--subtitle = "Hah, que fogos de artifício imundos."

# @p=55|description @t=array
n55--description = Luvas grossas e à prova de calor, com cheiro forte de pólvora

# @p=55|ability @t=array
n55--ability =
    +30% de raio de explosão para bombas acionadas por você
    Bombas têm chance de desencadear explosões em cadeia

## n56
# @p=56|name @t=array
n56--name = Misericórdia da Santa Donzela

# @p=56|subtitle @t=array
n56--subtitle = "Boa criança, boa criança..."

# @p=56|description @t=array
n56--description =
    Uma das vestes da freira, sedosa ao toque, inesquecível
    A radiância sagrada flui por suas fibras, oferecendo conforto

# @p=56|ability @t=array
n56--ability =
    Entra à força no Modo Sábio
    Ganha mais afinidade ao afagar a cabeça da \str[120]

## n57
# @p=57|name @t=array
n57--name = Recupere o Ichigo!

# @p=57|subtitle @t=array
n57--subtitle = {""}

# @p=57|description @t=array
n57--description =
    ASABA, consumido pela tristeza pelo morango perdido,⎵
    Libera sua arte suprema. Uma vez marcado, você é engolido
    Por uma tempestade inevitável de combos… Mas a tristeza permanece—
    queimado pelas emoções do destino, você herda esta técnica proibida!⎵

# @p=57|ability @t=array
n57--ability =
    Liberte um golpe especial com o comando correto⎵
    Quanto menor o seu PV, mais forte será o golpe especial

## n59
# @p=59|name @t=array
n59--name = Pingente Rubrum

# @p=59|subtitle @t=array
n59--subtitle = {""}

# @p=59|description @t=array
n59--description =
    A Preciosa Relíquia do Mago Caído.⎵
    Um pingente forjado a partir de uma pequena quantidade de Fragmento do Filósofo⎵
    Imbuído de um poder alquímico tênue, porém eterno

# @p=59|ability @t=array
n59--ability =
    Aumenta o ataque mágico com base na quantidade de Fragmentos do Filósofo em posse
    Reduz o desgaste da durabilidade da arma ao conjurar magia em \c[6]24%\c[0]

## n60
# @p=60|name @t=array
n60--name = Diadema do Mago Caído

# @p=60|subtitle @t=str
n60--subtitle = {""}

# @p=60|description @t=array
n60--description =
    Um círculo amaldiçoada, corrompida por magia negra,
    Assombrada por um rancor teimoso que corrói a carne

# @p=60|ability @t=array
n60--ability =
    Poder de ataque mágico +100%
    PV Máx -50%

## n61
# @p=61|name @t=array
n61--name = Manto do Mago Caído

# @p=61|subtitle @t=str
n61--subtitle = {""}

# @p=61|description @t=array
n61--description =
    Um manto amaldiçoado, corrompido por magia sombria,
    Assombrado por um espírito vingativo sedento por retribuição

# @p=61|ability @t=array
n61--ability =
    As pós-imagens criadas por Senpo permanecem por mais tempo
    Objetos tocados por elas ficam congelados no lugar

## n62
# @p=62|name @t=array
n62--name = Luvas do Mago Caído

# @p=62|subtitle @t=str
n62--subtitle = {""}

# @p=62|description @t=array
n62--description =
    Luvas amaldiçoadas manchadas por magia negra,
    Imbuídas de um espírito vingativo ansioso para atacar

# @p=62|ability @t=array
n62--ability = Projéteis perseguem inimigos próximos

## n63
# @p=63|name @t=array
n63--name = Botas do Mago Caído

# @p=63|subtitle @t=str
n63--subtitle = {""}

# @p=63|description @t=array
n63--description =
    Botas amaldiçoadas manchadas por magia negra,
    Imbuídas de um espírito vingativo que concede agilidade fantasmagórica

# @p=63|ability @t=array
n63--ability = Aumenta a velocidade de movimento, concede estado de vazio ao usar Senpo

## n65
# @p=65|name @t=array
n65--name = Faixa de Determinação

# @p=65|subtitle @t=array
n65--subtitle = "Quem diabos você pensa que eu sou!?"

# @p=65|description @t=array
n65--description =
    Uma faixa que desperta paixão quando usada
    Sem efeito real, mas com um espírito inabalável incomparável

# @p=65|ability @t=array
n65--ability =
    Reduz a chance de status anormal
    Tem uma pequena chance de resistir a dano fatal

## n67
# @p=67|name @t=array
n67--name = Braçadeiras do Artista Marcial

# @p=67|subtitle @t=str
n67--subtitle = {""}

# @p=67|description @t=array
n67--description =
    Braçadeiras enfaixadas usadas por artistas marciais durante os treinos
    Protegem as articulações enquanto melhoram a precisão dos movimentos

# @p=67|ability @t=array
n67--ability =
    — 12% de consumo de durabilidade da arma
    Velocidade de ataque aumentada e dano de combos desarmado reforçado

## n68
# @p=68|name @t=array
n68--name = Botas do Artista Marcial

# @p=68|subtitle @t=str
n68--subtitle = {""}

# @p=68|description @t=array
n68--description =
    Sapatos comumente usados por artistas marciais que
    Dominaram sua arte, irradiando uma aura poderosa

# @p=68|ability @t=array
n68--ability = Velocidade de movimento aumentada. Senpo aprimorado

## n69
# @p=69|name @t=array
n69--name = Quebra-Faces

# @p=69|subtitle @t=array
n69--subtitle = "Droga... eu só quero socar alguém na cara...!"

# @p=69|description @t=array
n69--description =
    Luvas de soco deixadas por um boxeador lendário.
    Ainda é possível sentir a força avassaladora que permanece nelas.

# @p=69|ability @t=array
n69--ability =
    Não é possível usar armas enquanto equipado
    Ataques de soco podem causar dano extra baseado no PV do alvo

## n70
# @p=70|name @t=array
n70--name = Coração do Espantalho

# @p=70|subtitle @t=str
n70--subtitle = {""}

# @p=70|description @t=array
n70--description =
    Um corpo oco de um espantalho
    Sem calor, sem batimento cardíaco — ainda assim pode viver em seu lugar

# @p=70|ability @t=array
n70--ability =
    Impede todas as formas de recuperação de PV enquanto equipado
    Com 0 PV, você permanece ativo por um pouco mais de tempo antes de cair

## n73
# @p=73|name @t=array
n73--name = Anel de Lava

# @p=73|subtitle @t=str
n73--subtitle = {""}

# @p=73|description @t=array
n73--description =
    Um anel forjado a partir de rocha que flui com magma escaldante
    Usá-lo alivia a dor tanto do gelo quanto da chama

# @p=73|ability @t=array
n73--ability =
    Reduz muito a chance de ser congelado
    Reduz a chance de ser queimado

## n74
# @p=74|name @t=array
n74--name = Volumen Salamandrae

# @p=74|subtitle @t=array
n74--subtitle = "Sim, eles realmente gostam de pimentas..."

# @p=74|description @t=array
n74--description =
    Um grimório encadernado com escamas de salamandra. Embora se assemelhe
    a uma enciclopédia, seus registros de salamandras que habitam vulcões⎵
    Concedem uma compreensão mais profunda sobre o fogo quando estudado.

# @p=74|ability @t=array
n74--ability = Fortalece o dano e a forma da magia do elemento fogo

## n75
# @p=75|name @t=array
n75--name = Olho do Demônio

# @p=75|subtitle @t=str
n75--subtitle = {""}

# @p=75|description @t=array
n75--description =
    Um globo ocular retirado de um demônio. Ele ainda está observando.⎵
    Demônios habilidosos em manipular mentes frequentemente possuem a capacidade⎵
    de ver através das coisas. Talvez ele permita que você perceba detalhes
     que, de outra forma, passariam despercebidos…

# @p=75|ability @t=array
n75--ability = Revela objetos e caminhos ocultos enquanto estiver equipado

## n77
# @p=77|name @t=array
n77--name = A Oração de uma Donzela

# @p=77|subtitle @t=array
n77--subtitle = Peixes… tantos peixes… pilhas de salmão…”

# @p=77|description @t=array
n77--description =
    Uma oração oferecida por uma arquidemônia obcecada por comer salmão
    Dizer que ela pode distorcer a realidade talvez seja um pouco de exagero…
    mas ela está, de fato, sincera e ansiosamente aguardando que oferendas cheguem

# @p=77|ability @t=array
n77--ability = Aumenta a chance de obter \ii[142] e \ii[143]

## n80
# @p=80|name @t=array
n80--name = Decreto Real

# @p=80|subtitle @t=str
n80--subtitle = {""}

# @p=80|description @t=array
n80--description =
    Um anel que simboliza a glória suprema de um verdadeiro rei
    Aumenta muito o moral dos seguidores!

# @p=80|ability @t=array
n80--ability =
    Aumenta um pouco todos os atributos
    Aumenta todos os servos e aprimora seus atributos especiais

## n100
# @p=100|name @t=array
n100--name = Unidade I Nexus

# @p=100|subtitle @t=str
n100--subtitle = {""}

# @p=100|description @t=array
n100--description =
    Um núcleo muito mais avançado que a tecnologia moderna, sua superfície brilhante⎵
    Com circuitos de energia misteriosos. Mesmo com a maioria das partes faltando,⎵
    Ainda mostra um poder incrível de detecção e computação

# @p=100|ability @t=array
n100--ability =
    Concede detecção de área quando equipado
    Aumentam os tipos dos objetos detectados conforme o nível do núcleo aumenta

## n125
# @p=125|name @t=array
n125--name = Atsu Atsu Bouzu

# @p=125|subtitle @t=str
n125--subtitle = {""}

# @p=125|description @t=array
n125--description =
    Um boneco de pano feito com as orações sinceras de alguém. Ele
    carrega desejos, trazendo pequenas mudanças aos padrões climáticos normais
    No entanto, o boneco desaparece silenciosamente em seguida

# @p=125|ability @t=array
n125--ability = Quando equipado, garante clima escaldante no dia seguinte

## n126
# @p=126|name @t=array
n126--name = Teru Teru Bouzu

# @p=126|subtitle @t=str
n126--subtitle = {""}

# @p=126|description @t=array
n126--description =
    Um boneco de pano feito com as orações sinceras de alguém. Ele
    Carrega desejos, trazendo pequenas mudanças aos padrões climáticos normais
    No entanto, o boneco desaparece silenciosamente em seguida

# @p=126|ability @t=array
n126--ability = Quando equipado, garante clima ensolarado no dia seguinte

## n127
# @p=127|name @t=array
n127--name = Kumo Kumo Bouzu

# @p=127|subtitle @t=str
n127--subtitle = {""}

# @p=127|description @t=array
n127--description =
    Um boneco de pano feito com as orações sinceras de alguém. Ele
    Carrega desejos, trazendo pequenas mudanças aos padrões climáticos normais
    No entanto, o boneco desaparece silenciosamente em seguida

# @p=127|ability @t=array
n127--ability = Quando equipado, garante clima nublado no dia seguinte

## n128
# @p=128|name @t=array
n128--name = Ame Ame Bouzu

# @p=128|subtitle @t=str
n128--subtitle = {""}

# @p=128|description @t=array
n128--description =
    Um boneco de pano feito com as orações sinceras de alguém. Ele
    Carrega desejos, trazendo pequenas mudanças aos padrões climáticos normais
    No entanto, o boneco desaparece silenciosamente em seguida

# @p=128|ability @t=array
n128--ability = Quando equipado, garante clima chuvoso no dia seguinte

## n129
# @p=129|name @t=array
n129--name = O sorriso de uma garota

# @p=129|subtitle @t=array
n129--subtitle = "\str[121], Você cumpriu bem a sua promessa!"

# @p=129|description @t=array
n129--description =
    A imouto-chan que sempre admirou e se preocupou com seu⎵
    \str[121] finalmente mostra um sorriso satisfeito
    Para \str[121], isso é suficiente para ser a motivação para continuar

# @p=129|ability @t=array
n129--ability = Desejo aumentado, todos os atributos aumentados

## n130
# @p=130|name @t=array
n130--name = calcinha da \str[120] foi removida

# @p=130|subtitle @t=array
n130--subtitle = "Ainda carrega o aroma da \str[120]..."

# @p=130|description @t=array
n130--description =
    Calcinha recebida da \str[120] devido a um mal-entendido
    Nunca devolvida, mas, no fundo, há felicidade
    bem no fundo, uma leve e silenciosa sensação de felicidade paira...

# @p=130|ability @t=array
n130--ability = Regenera o PV automaticamente quando abaixo de 50%

## n131
# @p=131|name @t=array
n131--name = Coelho de Pelúcia

# @p=131|subtitle @t=array
n131--subtitle = "Waaah—! Não rasgue ele~~!"

# @p=131|description @t=array
n131--description =
    Um coelho de pelúcia que \str[120] sempre carrega⎵
    Seus braços, impregnado com seu aroma
    Pensando bem… por que isso está em minhas mãos?

# @p=131|ability @t=array
n131--ability = {""}

## n147
# @p=147|name @t=array
n147--name = Curativo

# @p=147|subtitle @t=str
n147--subtitle = {""}

# @p=147|description @t=array
n147--description = {""}

# @p=147|ability @t=empty_array
n147--ability = ⊘

## n150
# @p=150|name @t=array
n150--name = Camiseta Bônus

# @p=150|subtitle @t=str
n150--subtitle = {""}

# @p=150|description @t=array
n150--description =
    Uma roupa feita sob medida pelo cavaleiro,
    Supostamente para promover o jogo
    Mas eu realmente não quero usá-la

# @p=150|ability @t=empty_array
n150--ability = ⊘

## n152
# @p=152|name @t=array
n152--name = Pijama da \str[120]

# @p=152|subtitle @t=str
n152--subtitle = {""}

# @p=152|description @t=array
n152--description =
    Um pijama de camisola que \str[120] geralmente usa,⎵
    Decorado com os laços que ela ama.
    Pensando bem… por que isso está em minhas mãos?

# @p=152|ability @t=empty_array
n152--ability = ⊘

## n153
# @p=153|name @t=array
n153--name = Shortinho da \str[120]

# @p=153|subtitle @t=str
n153--subtitle = {""}

# @p=153|description @t=array
n153--description =
    Shortinho macio e fofinho que \str[120] geralmente usa,⎵
    Decorado com os laços que ela ama.
    Pensando bem… por que isso está em minhas mãos?

# @p=153|ability @t=empty_array
n153--ability = ⊘

## n154
# @p=154|name @t=array
n154--name = Calcinha azul e branca

# @p=154|subtitle @t=str
n154--subtitle = {""}

# @p=154|description @t=array
n154--description = {""}

# @p=154|ability @t=empty_array
n154--ability = ⊘

## n155
# @p=155|name @t=array
n155--name = Calcinha rosa e branca

# @p=155|subtitle @t=str
n155--subtitle = {""}

# @p=155|description @t=array
n155--description = {""}

# @p=155|ability @t=empty_array
n155--ability = ⊘

## n156
# @p=156|name @t=array
n156--name = Calcinha branca

# @p=156|subtitle @t=str
n156--subtitle = {""}

# @p=156|description @t=array
n156--description = {""}

# @p=156|ability @t=empty_array
n156--ability = ⊘

## n157
# @p=157|name @t=array
n157--name = Curativo

# @p=157|subtitle @t=str
n157--subtitle = {""}

# @p=157|description @t=array
n157--description = {""}

# @p=157|ability @t=empty_array
n157--ability = ⊘

## n159
# @p=159|name @t=array
n159--name = Sem calcinha...

# @p=159|subtitle @t=str
n159--subtitle = {""}

# @p=159|description @t=array
n159--description = {""}

# @p=159|ability @t=empty_array
n159--ability = ⊘

## n296
# @p=296|name @t=array
n296--name = Martelo da sorte da Ruika

# @p=296|subtitle @t=array
n296--subtitle = "A chefe Maid-Ruika sempre o usa para bater em coelhos desobedientes."

# @p=296|description @t=array
n296--description =
    Um tesouro escondido das Coelhas-Maid, dizem ser o motivo de terem⎵
    Dominado o mercado tão rápido. Com um leve movimento, garante desejos ao portador—
    Aventureiros costumam ver consertando máquinas quebradas por arruaceiros

# @p=296|ability @t=array
n296--ability = Aumenta a chance de dropar ítens de dinheiro

## n297
# @p=297|name @t=array
n297--name = Kit de primeiros socorros da Mio

# @p=297|subtitle @t=array
n297--subtitle = "Droga! Eu caí no buraco de novo!?"

# @p=297|description @t=array
n297--description =
    Originalmente, uma ferramenta usada pelo dev para testar o sistemas de cura⎵
    mas ele acabou esquecendo de apagar. Ainda é inútil⎵
    Contra coisas que podem causar hit kill

# @p=297|ability @t=array
n297--ability = Restaura 100% do PV por segundo quando equipado

## n298
# @p=298|name @t=array
n298--name = Dedo dourado de Shiroin

# @p=298|subtitle @t=array
n298--subtitle =
    "Você sabe que isso vai estragar o jogo né?"
    "Eu sei."
    "E ainda assim você quer equipar?"
    "Claro que sim."

# @p=298|description @t=array
n298--description = Uma relíquia que turna tudo que toca em ouro — o sonho de quem se apaixonou por uma arma.

# @p=298|ability @t=array
n298--ability = Armas não quebram mais ao atacar

## n299
# @p=299|name @t=array
n299--name = Território Absoluto

# @p=299|subtitle @t=array
n299--subtitle = {""}

# @p=299|description @t=array
n299--description =
    O espaço sagrado entre a minissaia de uma garota e suas meias 3/4
    Não apenas concede alta resistência mágica, mas também a habilidade⎵
    Absurda de tirar todo tipo de item debaixo da saia à vontade

# @p=299|ability @t=array
n299--ability =
    Aumenta a capacidade de transportar armas em +99
    Aumenta a capacidade de transportar equipamentos em +99

## n300
# @p=300|name @t=array
n300--name = Catalisador Amatoria

# @p=300|subtitle @t=array
n300--subtitle = "Me dê o seu amor—! Caso contrário, vamos apenas morrer juntos~~~!"

# @p=300|description @t=array
n300--description =
    Um artefato proibido forjado por uma certa arquidemônia yandere
    Faz com que qualquer um que tocar se apaixone à força pelo portador
    Ignorando sua vontade

# @p=300|ability @t=array
n300--ability = Aumenta grandemente os atributos ganhos ao afagar \str[120]
