# Auto-generated by json_to_ftl.py

# @k=skillToggle
skillToggle = Ativada
    .i1 = Desativada

# @k=1
n1 = {""}
    # @p=name @t=array
    .name = Bolsa de Armazenamento Mágica
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = Uma ferramenta mágica portátil que lhe permite carregar⎵
    .description-i1 = muito mais itens do que o normal. No entanto,⎵
    .description-i2 = mesmo ferramentas mágicas têm seus limites de armazenamento..
    # @p=ability @t=array
    .ability = Capacidade de Armas: {"${QJ.MPMZ.tl.ex_playerCheckInventory('weapon')}"}
    .ability-i1 = Capacidade de Acessórios: {"${QJ.MPMZ.tl.ex_playerCheckInventory('gear')}"}

# @k=2
n2 = {""}
    # @p=name @t=array
    .name = Senpo
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = Um passo rápido no chão cobre uma curta distância,
    .description-i1 = permitindo que você esquive de alguns ataques. É apenas uma técnica de movimento⎵
    .description-i2 = inicial, mas o usuário insiste em dar um nome maneiro
    # @p=ability @t=array
    .ability = Segure a Barra de Espaço para ativar

# @k=3
n3 = {""}
    # @p=name @t=array
    .name = Senpo Tachi
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = Uma técnica de sacar a espada apreendida com o jovem Espadachim.
    .description-i1 = Combinada com SenPo, você liberta um golpe com o encantamento da⎵
    .description-i2 = rapidez — suficiente para derrubar inimigos se bem sincronizada.
    # @p=ability @t=array
    .ability = Clique esquerdo durante SenPo: Dano de corte aumenta com a velocidade
    .ability-i1 = Mantenha o botão direito pressionado durante o Senpo: Investe, efeitos escala com momentum
    # @p=mobileAbility @t=array
    .mobileAbility = Toque o botão da habilidade para cortar, dano aumenta com a velocidade de movimento
    .mobileAbility-i1 = Segure o botão da habilidade para uma Investida, efeito aumento com o momentum

# @k=4
n4 = {""}
    # @p=name @t=array
    .name = Golpe Redemoinho
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = Girando enquanto empunha a sua arma para atacar continuamente.⎵
    .description-i1 = A velocidade aumenta com o tempo. Para aqueles que não são bons ⎵
    .description-i2 = com técnicas de espadas, esse movimento é efetivo e fácil de aprender.
    # @p=ability @t=array
    .ability = Mantenha pressionado o botão direito para ativar a habilidade
    .ability-i1 = largue o botão para lançar sua arma
    # @p=mobileAbility @t=array
    .mobileAbility = Segure o botão da habilidade para iniciar o ataque
    .mobileAbility-i1 = Largue o botão durante o giro para lançar a sua arma

# @k=6
n6 = {""}
    # @p=name @t=array
    .name = Perverso Sortudo
    # @p=subtitle @t=array
    .subtitle = verdadeiro
    # @p=description @t=array
    .description = Uma lendária constituição pervertida que ativa por conta própria,⎵
    .description-i1 = mesmo sem que o usuário repare.
    .description-i2 = Como se abençoado e guiado por uma deusa invisível, forças irresistíveis⎵
    .description-i3 = te induzindo para cenários que aceleram o coração de fanservice…!
    # @p=ability @t=array
    .ability = Sempre cria as oportunidades perfeitas para acionar eventos pervertidos!

# @k=7
n7 = {""}
    # @p=name @t=array
    .name = Senso de Perigo
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = Muitas vezes chamado de "Olho da mente", mas na verdade é um sentido⎵
    .description-i1 = afiado por incontáveis escapadas da morte.
    .description-i2 = Em outras palavras, é mais um reflexo de trauma do que uma habilidade...
    # @p=ability @t=array
    .ability = Passe o mouse sobre o alvo para ver suas informações detalhadas
    # @p=mobileAbility @t=array
    .mobileAbility = Toque no alvo para ver informações detalhadas

# @k=10
n10 = {""}
    # @p=name @t=array
    .name = Supressão da Respiração
    # @p=subtitle @t=array
    .subtitle = verdadeiro
    # @p=description @t=array
    .description = Uma técnica ninja. Eu acabei aprendendo de forma apressada, mas…
    .description-i1 = de alguma forma, eu peguei o jeito bem rápido.
    # @p=ability @t=array
    .ability = Pressione Shift enquanto ativo para entrar no modo furtivo
    .ability-i1 = Reduz o alcance de detecção do monstro em \c[17]{"${1+$gameParty.leader().skillMasteryLevel(10)}"}\c[108] bloco
    .ability-i2 = Reduz a razão de percepção da \str[120] quando espiando por \c[17]{"${15+15*$gameParty.leader().skillMasteryLevel(10)}"}%\c[0]

# @k=11
n11 = {""}
    # @p=name @t=array
    .name = Golpe pelas Costas
    # @p=subtitle @t=array
    .subtitle = verdadeiro
    # @p=description @t=array
    .description = Uma técnica do ninja. Pode ser ativada quando estiver no modo furtivo
    .description-i1 = Ataca um inimigo desavisado pelas costas causando um dano imenso!
    # @p=ability @t=array
    .ability = Proficiência de Habilidade: \c[6]{"${$gameActors.actor(1).skillMasteryUses(11)}"}\c[0]
    .ability-i1 = Bônus de Dano de Assassinato: \c[17]{"${Math.round(200 + (2333 - 200) * Math.pow($gameActors.actor(1).skillMasteryLevel(11) / 9, 1.8))}"}%\c[0]

# @k=12
n12 = {""}
    # @p=name @t=array
    .name = Fluxo Explosivo de Musou
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = Uma técnica de finalização herdada do ASABA, aquele que abraçou a tristeza
    .description-i1 = em um instante rápido de mais para os olhos conseguirem ver, cem⎵
    .description-i2 = golpes, deixando o inimigo com nada além da escuridão final!
    # @p=ability @t=array
    .ability = Comando da habilidade:  {"{"}⬆⬇⬅⮕⬆⬇{"}"}
    .ability-i1 = Cada uso da habilidade consome algum PV

# @k=15
n15 = {""}
    # @p=name @t=array
    .name = Travestindo
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = Você botou roupas que não foram feitas pra você… e algo dentro de você⎵
    .description-i1 = se agitou. Sem bônus de combate, pode até mesmo mexer um pouco com a sua cabeça.
    .description-i2 = Seus parceiros te olham estranhamente, e inimigos podem esperar… talvez.
    .description-i3 = Afinal, neste mundo a fofura é justiça!
    # @p=ability @t=array
    .ability = Aumenta o Pecado baseado em quantidades de roupas femininas equipadas!

# @k=16
n16 = {""}
    # @p=name @t=array
    .name = Guardiões de Lâminas
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = "Não importa como você maneja suas armas!" "Nós nos levantaremos ao seu chamado!"
    .description-i1 = "Para impedir que as lâminas se desgastem!" "Para proteger a dignidade dos armamentos!"
    .description-i2 = "Pois nós acreditamos que as espadas são os mestres e os humanos os servos!"
    .description-i3 = "Os que tem a fé mais absurda, porém inabalável!"
    .description-i4 = "Nós somos — Preservadores de Armas — os guardiões das lâminas!"
    # @p=ability @t=array
    .ability = Vestir o distintivo faz você um de nós agora

# @k=18
n18 = {""}
    # @p=name @t=array
    .name = Quebra de Armas
    # @p=subtitle @t=array
    .subtitle = {""}
    # @p=description @t=array
    .description = Todas as armas tem seu limite de durabilidade,⎵
    .description-i1 = e o usuário não sendo bom em ataques precisos.
    .description-i2 = há o risco de quebrá-las. Mas quando a arma quebra —
    .description-i3 = ela infligi um poderoso ataque crítico!
    # @p=ability @t=array
    .ability = Aumento do dano final: \c[6]{"${200+(100*$gameActors.actor(1).skillMasteryLevel(48))}"}%\c[0]

# @k=26
n26 = {""}
    # @p=name @t=array
    .name = Treinamento de Espadachim
    # @p=subtitle @t=array
    .subtitle = verdadeiro
    # @p=description @t=array
    .description = Buscou conselhos de uma espadachim de como ficar mais forte
    .description-i1 = Tudo que ela disse foi "Basta dar 1.000 golpes de espada todos os dias!"
    .description-i2 = —Será que isso vai mesmo funcionar!? De qualquer forma, vamos tentar...
    # @p=ability @t=array
    .ability = Golpes de Treino Concluídos: {\c[6]{"${QJ.MPMZ.tl.playerSwordsmanshipTraining(1)}"}\c[0]
    .ability-i1 = Dano base de ataque de armas corpo a corpo aumentado em \c[6]{"${QJ.MPMZ.tl.playerSwordsmanshipTraining(2)}"}%
