# Auto-generated by json_to_ftl.py

# @p=skillToggle @t=array
skillToggle =
    Ativada
    Desativada
# @p=1|name @t=array
n1--name = Bolsa de Armazenamento Mágica
# @p=2|name @t=array
n2--name = Senpo
