# Auto-generated by json_to_ftl.py

# @k=gameTitle
gameTitle = Uma Vida Simples com Minha Imouto Discreta⎵

# @k=goldHeld
goldHeld = Ouro

# @k=quantityHeld
quantityHeld = \fs[16]•Quantidade Possuída:\c[17] ${} \c[0]\py[-8]

# @k=autoUpdate
autoUpdate = Atualização disponível: Dados do jogo da versão ${} detectados.⎵
    .i1 = Gostaria de baixar e atualizar agora?

# @k=fullScreen
fullScreen = Tela Cheia

# @k=masterVolume
masterVolume = Volume Geral

# @k=voiceVolume
voiceVolume = Volume da Voz

# @k=BgmVolume
BgmVolume = Volume da Música

# @k=BgsVolume
BgsVolume = Volume do Ambiente

# @k=SeVolume
SeVolume = Volume dos Efeitos Sonoros

# @k=MaxPlayerMsgs
MaxPlayerMsgs = Máx. de Mensagens por Jogador

# @k=GameFAQ
GameFAQ = Guia do Jogo

# @k=ShowWeaponDurability
ShowWeaponDurability = Mostrar Durabilidade da Arma

# @k=DisableAutoUpdate
DisableAutoUpdate = Desativar Atualização Automática

# @k=LockedFPS
LockedFPS = Travar a 60 FPS

# @k=Language
Language = Idioma do Jogo

# @k=SwitchLanguage
SwitchLanguage = Mudança de idioma do jogo detectado!
    .i1 = Reiniciando agora para aplicar as novas configurações de idioma!

# @k=ErrorReport
ErrorReport = Um erro ocorreu. Pedimos que relate o bug no servidor do Discord do NLCH.
    .i1 = (Clique em "OK" para abrir o link de convite)
    .i2 = (Anexe uma captura de tela do erro)

# @k=UpdateComplete1
UpdateComplete1 = Atualização do jogo concluída!
    .i1 = O jogo será reiniciado automaticamente após fechar esta janela.
    .i2 = Você pode carregar o salvamento automático para continuar sua jornada!

# @k=UpdateComplete2
UpdateComplete2 = Atualização do jogo concluída!
    .i1 = O jogo será reiniciado em breve para aplicar a atualização!

# @k=RemindToUpdate
RemindToUpdate = Ocorreu um erro e o jogo está travado.
    .i1 = Um patch mais recente está disponível—
    .i2 = Por favor, use a atualização automática para corrigir o problema!

# @k=bagFull
bagFull = Limite de inventário excedido!

# @k=noStatusEffects
noStatusEffects = Sem efeitos de status!

# @k=unimplementedDoor
unimplementedDoor = Esta porta não vai abrir deste lado

# @k=zipUpdateComplete
zipUpdateComplete = Atualização instalada com sucesso.⎵
    .i1 = Reiniciando o jogo para aplicar a atualização!

# @k=zipUpdateFail
zipUpdateFail = Erro ao extrair e instalar atualizações!
    .i1 = Por favor, tente atualizar automaticamente novamente ou
    .i2 = extraia manualmente os arquivos da atualização para instalar!

# @k=fileDownloadedSuccessfully
fileDownloadedSuccessfully = ${} baixado com sucesso!

# @k=fileDownloadFailed
fileDownloadFailed = ${} falhou ao baixar! Tente novamente agora!

# @k=installPatch
installPatch = A atualização requer extração — instalando agora. Isso pode causar lentidão no jogo, por favor, seja paciente!

# @k=totalFilesToUpdate
totalFilesToUpdate = Foram detectados ${} arquivo(s) para atualizar — começando a baixar os arquivos!

# @k=silentUpdateSuccess
silentUpdateSuccess = Novo patch de conteúdo para ${} foi instalado com sucesso e entrará em vigor na próxima reinicialização.

# @k=outdatedVersionWarning
outdatedVersionWarning = Sua atual versão do jogo está desatualizada. A versão mais recente é ${}.
    .i1 = Atualizações de versão principal não suportam atualizações automáticas.⎵
    .i2 = Por favor, baixe o jogo novamente de uma fonte oficial.

# @k=renameCharacter
renameCharacter = Lembrei agora—
    .i1 = ela é...

# @k=heroName
heroName = Onii-chan

# @k=heroineName
heroineName = Imouto

# @k=nonHardwareAccelerated
nonHardwareAccelerated = O jogo está sendo executado na placa gráfica integrada!
    .i1 = Se o seu PC tiver uma GPU dedicada, recomendamos configurar o Game.exe⎵
    .i2 = para usá-la no painel de controle gráfico para uma experiência de jogo mais fluida.

# @k=isAmdCPU
isAmdCPU = Seu CPU foi identificado como um processador AMD.
    .i1 = Alguns processadores AMD podem ter queda de quadros ao reproduzir vídeos VP9 (WebM)⎵
    .i2 = em um ambiente Chromium. Se você encontrar esse problema, tente forçar o jogo
    .i3 = a usar renderização via GPU ou atualize seus drivers para ajudar a amenizar a situação.

# @k=failedToLoad
failedToLoad = Este tipo de problema pode ser causado por:
    .i1 = ① Arquivos do jogo corrompidos ou nomes de arquivos ilegíveis devido a problemas de codificação durante a extração/instalação.
    .i2 = ② O desenvolvedor esqueceu de incluir o arquivo — aguarde uma atualização/patch para corrigir o problema.

# @k=LowResMode
LowResMode = Modo Gráfico Baixo

# @k=lowResModeWarning
lowResModeWarning = Essa função melhora o desempenho em dispositivos Android, essa função deve ter pouco ou nenhum efeito na versão de PC.
    .i1 = Quando ativada, o jogo renderiza mapas e imagens em uma resolução mais baixa e então faz o upscaling,⎵
    .i2 = reduzindo a carga da GPU em dispositivos móveis, baixando a temperatura e consumo de bateria.
    .i3 = Nota: Essa é uma função experimental e sua eficiência pode variar dependendo do dispositivo.
    .i4 = Você pode desabilitar essa função a qualquer momento para restaurar imediatamente a resolução da imagem.

# @k=cloudSaveServiceWarning
cloudSaveServiceWarning = Como o banco de dados de save da nuvem ainda está em construção,
    .i1 = este recurso temporariamente solicitará acesso ao seu Google Drive
    .i2 = para poder armazenar os arquivos de salvamento do jogo na pasta NLCH/save.
    .i3 = Arquivos de save enviados serão usados somente para futura sincronização e⎵
    .i4 = restaurá-los de volta ao jogo e não serão usados para quaisquer outros fins.
    .i5 = Você concorda em conceder ao jogo acesso ao Google Drive?

# @k=uploadSaveFile
uploadSaveFile = Baixar um arquivo de salvamento do Google Drive substituirá os dados de salvamento locais atuais!
    .i1 = Você deseja continuar?

# @k=nearbyMonstersCount
nearbyMonstersCount = Monstro detectado nas proximidades

# @k=nearbyTreasuresCount
nearbyTreasuresCount = Tesouro detectado nas proximidades

# @k=underwaterTreasuresCount
underwaterTreasuresCount = Tesouro submerso detectado nas proximidades

# @k=steamWishlist
steamWishlist = Nossa página na loja da Steam finalmente está ativa!
    .i1 = Por favor, adicione-nos a sua lista de desejos e apoie-nos! (*´∀`)~♥
    .i2 = ⬇Clique abaixo para abrir a página da Steam.

# @k=memberMenu
memberMenu = {""}
    # @p=firstTimeNotice @t=array
    .firstTimeNotice = Esta funcionalidade de verificação de propriedade está atualmente em fase experimental.
    .firstTimeNotice-i1 = Você pode entrar com o Patreon aqui,⎵
    .firstTimeNotice-i2 = ou vincular sua conta do Itch para verificação de propriedade.
    .firstTimeNotice-i3 = Se você tiver uma assinatura ativa
    .firstTimeNotice-i4 = ou já possuir o jogo no Itch,
    .firstTimeNotice-i5 = poderá usar recursos como atualização automática de grandes atualizações.
    .firstTimeNotice-i6 = 
    .firstTimeNotice-i7 = Observação:
    .firstTimeNotice-i8 = No momento, a verificação está disponível apenas para jogadores⎵
    .firstTimeNotice-i9 = que compraram o jogo no Itch ou no Patreon,⎵
    .firstTimeNotice-i10 = ou para jogadores com uma assinatura paga no Patreon.
    # @p=shortHint @t=str
    .shortHint = ⎵Agora é possível ativar salvamentos na nuvem e grandes atualizações
    # @p=waitingLogin @t=str
    .waitingLogin = Aguardando a conclusão do login...
    # @p=notLoggedIn @t=str
    .notLoggedIn = Não está logado
    # @p=RequestingLogin @t=str
    .RequestingLogin = Solicitando link de login...
    # @p=openingWindow @t=str
    .openingWindow = Abrindo janela de login no Patreon...
    # @p=cloudSave @t=str
    .cloudSave = Usar Salvamento na Nuvem
    # @p=logInFirst @t=str
    .logInFirst = Por favor, clique neste botão para entrar primeiro
    # @p=CheckUpdates @t=str
    .CheckUpdates = Atualize para a versão mais recente
    # @p=Subscribed @t=str
    .Subscribed = Assinatura confirmada!
    # @p=subscribedAndItchUser @t=str
    .subscribedAndItchUser = Assinatura confirmada! (Propriedade no Itch verificada)
    # @p=NotSubscribed @t=str
    .NotSubscribed = Nenhuma assinatura ativa detectada. Alguns recursos estão indisponíveis.
    # @p=lastCheck @t=str
    .lastCheck = Última verificação:⎵
    # @p=checkLatestVersion @t=str
    .checkLatestVersion = Procurando versão mais recente, por favor aguarde...
    # @p=isLatestVersion @t=str
    .isLatestVersion = Você já está na versão mais recente!
    # @p=notSponsor @t=str
    .notSponsor = Usuários não verificados devem se inscrever primeiro!
    # @p=ImoutoFavorite @t=str
    .ImoutoFavorite = O(A) Favorito(a) da Imouto
    # @p=itchUser @t=str
    .itchUser = Usuário do Itch confirmado!
    # @p=nonItchUser @t=str
    .nonItchUser = Este jogo não foi encontrado na sua biblioteca do Itch!
    # @p=itchVerifyNotice @t=str
    .itchVerifyNotice = Você pode verificar a propriedade da versão do Itch aqui
    # @p=itchVerifyAlert @t=str
    .itchVerifyAlert = Por favor, faça login antes de verificar a versão do Itch!
    # @p=majorUpdateFailed @t=array
    .majorUpdateFailed = Falha na atualização da versão principal!
    .majorUpdateFailed-i1 = Código de erro: ${}
    .majorUpdateFailed-i2 = Tente fazer o login para verificação e iniciar a atualização novamente,
    .majorUpdateFailed-i3 = ou envie esta print em nosso servidor do Discord para assistência!

# @k=AdventurersPathway
AdventurersPathway = {""}
    # @p=mapName @t=str
    .mapName = ⎵ – Caminho do Aventureiro –⎵

# @k=ShallowRuinsLabyrinth
ShallowRuinsLabyrinth = {""}
    # @p=mapName @t=str
    .mapName = – Labirinto das Ruínas Rasas –
    # @p=mapDescription @t=str
    .mapDescription = Um vasto labirinto repleto de inúmeros mistérios⎵

# @k=ForgottenCatacombe
ForgottenCatacombe = {""}
    # @p=mapName @t=str
    .mapName = ⎵– Catacumba Esquecida – ⏎

# @k=ForestofRuins
ForestofRuins = {""}
    # @p=mapName @t=str
    .mapName = ⎵– Floresta das Ruínas –⎵

# @k=AbandonedForest
AbandonedForest = {""}
    # @p=mapName @t=str
    .mapName = ⎵– Floresta Abandonada –⎵

# @k=ExcavationSite
ExcavationSite = {""}
    # @p=mapName @t=str
    .mapName = ⎵– Sítio de Escavação –⎵

# @k=TheFallenChurch
TheFallenChurch = {""}
    # @p=mapName @t=str
    .mapName = ⎵– A Igreja Caída –⎵

# @k=DoorofStar
DoorofStar = {""}
    # @p=mapName @t=str
    .mapName = ⎵– Porta da Estrela –⎵

# @k=ScorchingLavaZone
ScorchingLavaZone = {""}
    # @p=mapName @t=str
    .mapName = – Zona de Lava Escaldante –
    # @p=mapDescription @t=str
    .mapDescription = ⎵Uma terra ardente entrelaçada pelo fogo, onde as provações queimam eternamente⎵

# @k=Nibelungen
Nibelungen = {""}
    # @p=mapName @t=str
    .mapName = ⎵– Nibelungen –⎵
