# Auto-generated by json_to_ftl.py

# @p=gameTitle @t=array
gameTitle = Uma Vida Simples com Minha Imouto Discreta⎵

# @p=goldHeld @t=array
goldHeld = Ouro

# @p=quantityHeld @t=array
quantityHeld = \fs[16]•Quantidade Possuída:\c[17] {"${}"} \c[0]\py[-8]

# @p=autoUpdate @t=array
autoUpdate =
    Atualização disponível: Dados do jogo da versão {"${}"} detectados.⎵
    Gostaria de baixar e atualizar agora?

# @p=fullScreen @t=array
fullScreen = Tela Cheia

# @p=masterVolume @t=array
masterVolume = Volume Geral

# @p=voiceVolume @t=array
voiceVolume = Volume da Voz

# @p=BgmVolume @t=array
BgmVolume = Volume da Música

# @p=BgsVolume @t=array
BgsVolume = Volume do Ambiente

# @p=SeVolume @t=array
SeVolume = Volume dos Efeitos Sonoros

# @p=MaxPlayerMsgs @t=array
MaxPlayerMsgs = Máx. de Mensagens por Jogador

# @p=GameFAQ @t=array
GameFAQ = Guia do Jogo

# @p=ShowWeaponDurability @t=array
ShowWeaponDurability = Mostrar Durabilidade da Arma

# @p=DisableAutoUpdate @t=array
DisableAutoUpdate = Desativar Atualização Automática

# @p=LockedFPS @t=array
LockedFPS = Travar a 60 FPS

# @p=Language @t=array
Language = Idioma do Jogo

# @p=SwitchLanguage @t=array
SwitchLanguage =
    Mudança de idioma do jogo detectado!
    Reiniciando agora para aplicar as novas configurações de idioma!

# @p=ErrorReport @t=array
ErrorReport =
    Um erro ocorreu. Pedimos que relate o bug no servidor do Discord do NLCH.
    (Clique em "OK" para abrir o link de convite)
    (Anexe uma captura de tela do erro)

# @p=UpdateComplete1 @t=array
UpdateComplete1 =
    Atualização do jogo concluída!
    O jogo será reiniciado automaticamente após fechar esta janela.
    Você pode carregar o salvamento automático para continuar sua jornada!

# @p=UpdateComplete2 @t=array
UpdateComplete2 =
    Atualização do jogo concluída!
    O jogo será reiniciado em breve para aplicar a atualização!

# @p=RemindToUpdate @t=array
RemindToUpdate =
    Ocorreu um erro e o jogo está travado.
    Um patch mais recente está disponível—
    Por favor, use a atualização automática para corrigir o problema!

# @p=bagFull @t=array
bagFull = Limite de inventário excedido!

# @p=noStatusEffects @t=array
noStatusEffects = Sem efeitos de status!

# @p=unimplementedDoor @t=array
unimplementedDoor = Esta porta não vai abrir deste lado

# @p=zipUpdateComplete @t=array
zipUpdateComplete =
    Atualização instalada com sucesso.⎵
    Reiniciando o jogo para aplicar a atualização!

# @p=zipUpdateFail @t=array
zipUpdateFail =
    Erro ao extrair e instalar atualizações!
    Por favor, tente atualizar automaticamente novamente ou
    extraia manualmente os arquivos da atualização para instalar!

# @p=fileDownloadedSuccessfully @t=array
fileDownloadedSuccessfully = {"${}"} baixado com sucesso!

# @p=fileDownloadFailed @t=array
fileDownloadFailed = {"${}"} falhou ao baixar! Tente novamente agora!

# @p=installPatch @t=array
installPatch = A atualização requer extração — instalando agora. Isso pode causar lentidão no jogo, por favor, seja paciente!

# @p=totalFilesToUpdate @t=array
totalFilesToUpdate = Foram detectados {"${}"} arquivo(s) para atualizar — começando a baixar os arquivos!

# @p=silentUpdateSuccess @t=array
silentUpdateSuccess = Novo patch de conteúdo para {"${}"} foi instalado com sucesso e entrará em vigor na próxima reinicialização.

# @p=outdatedVersionWarning @t=array
outdatedVersionWarning =
    Sua atual versão do jogo está desatualizada. A versão mais recente é {"${}"}.
    Atualizações de versão principal não suportam atualizações automáticas.⎵
    Por favor, baixe o jogo novamente de uma fonte oficial.

# @p=renameCharacter @t=array
renameCharacter =
    Lembrei agora—
    ela é...

# @p=heroName @t=array
heroName = Onii-chan

# @p=heroineName @t=array
heroineName = Imouto

# @p=nonHardwareAccelerated @t=array
nonHardwareAccelerated =
    O jogo está sendo executado na placa gráfica integrada!
    Se o seu PC tiver uma GPU dedicada, recomendamos configurar o Game.exe⎵
    para usá-la no painel de controle gráfico para uma experiência de jogo mais fluida.

# @p=isAmdCPU @t=array
isAmdCPU =
    Seu CPU foi identificado como um processador AMD.
    Alguns processadores AMD podem ter queda de quadros ao reproduzir vídeos VP9 (WebM)⎵
    em um ambiente Chromium. Se você encontrar esse problema, tente forçar o jogo
    a usar renderização via GPU ou atualize seus drivers para ajudar a amenizar a situação.

# @p=failedToLoad @t=array
failedToLoad =
    Este tipo de problema pode ser causado por:
    ① Arquivos do jogo corrompidos ou nomes de arquivos ilegíveis devido a problemas de codificação durante a extração/instalação.
    ② O desenvolvedor esqueceu de incluir o arquivo — aguarde uma atualização/patch para corrigir o problema.

# @p=LowResMode @t=array
LowResMode = Modo Gráfico Baixo

# @p=lowResModeWarning @t=array
lowResModeWarning =
    Essa função melhora o desempenho em dispositivos Android, essa função deve ter pouco ou nenhum efeito na versão de PC.
    Quando ativada, o jogo renderiza mapas e imagens em uma resolução mais baixa e então faz o upscaling,⎵
    reduzindo a carga da GPU em dispositivos móveis, baixando a temperatura e consumo de bateria.
    Nota: Essa é uma função experimental e sua eficiência pode variar dependendo do dispositivo.
    Você pode desabilitar essa função a qualquer momento para restaurar imediatamente a resolução da imagem.

# @p=cloudSaveServiceWarning @t=array
cloudSaveServiceWarning =
    Como o banco de dados de save da nuvem ainda está em construção,
    este recurso temporariamente solicitará acesso ao seu Google Drive
    para poder armazenar os arquivos de salvamento do jogo na pasta NLCH/save.
    Arquivos de save enviados serão usados somente para futura sincronização e⎵
    restaurá-los de volta ao jogo e não serão usados para quaisquer outros fins.
    Você concorda em conceder ao jogo acesso ao Google Drive?

# @p=uploadSaveFile @t=array
uploadSaveFile =
    Baixar um arquivo de salvamento do Google Drive substituirá os dados de salvamento locais atuais!
    Você deseja continuar?

# @p=nearbyMonstersCount @t=array
nearbyMonstersCount = Monstro detectado nas proximidades

# @p=nearbyTreasuresCount @t=array
nearbyTreasuresCount = Tesouro detectado nas proximidades

# @p=underwaterTreasuresCount @t=array
underwaterTreasuresCount = Tesouro submerso detectado nas proximidades

# @p=steamWishlist @t=array
steamWishlist =
    Nossa página na loja da Steam finalmente está ativa!
    Por favor, adicione-nos a sua lista de desejos e apoie-nos! (*´∀`)~♥
    ⬇Clique abaixo para abrir a página da Steam.

# @p=memberMenu|firstTimeNotice @t=array
memberMenu--firstTimeNotice =
    Esta funcionalidade de verificação de propriedade está atualmente em fase experimental.
    Você pode entrar com o Patreon aqui,⎵
    ou vincular sua conta do Itch para verificação de propriedade.
    Se você tiver uma assinatura ativa
    ou já possuir o jogo no Itch,
    poderá usar recursos como atualização automática de grandes atualizações.
    
    Observação:
    No momento, a verificação está disponível apenas para jogadores⎵
    que compraram o jogo no Itch ou no Patreon,⎵
    ou para jogadores com uma assinatura paga no Patreon.

# @p=memberMenu|shortHint @t=str
memberMenu--shortHint = ⎵Agora é possível ativar salvamentos na nuvem e grandes atualizações

# @p=memberMenu|waitingLogin @t=str
memberMenu--waitingLogin = Aguardando a conclusão do login...

# @p=memberMenu|notLoggedIn @t=str
memberMenu--notLoggedIn = Não está logado

# @p=memberMenu|RequestingLogin @t=str
memberMenu--RequestingLogin = Solicitando link de login...

# @p=memberMenu|openingWindow @t=str
memberMenu--openingWindow = Abrindo janela de login no Patreon...

# @p=memberMenu|cloudSave @t=str
memberMenu--cloudSave = Usar Salvamento na Nuvem

# @p=memberMenu|logInFirst @t=str
memberMenu--logInFirst = Por favor, clique neste botão para entrar primeiro

# @p=memberMenu|CheckUpdates @t=str
memberMenu--CheckUpdates = Atualize para a versão mais recente

# @p=memberMenu|Subscribed @t=str
memberMenu--Subscribed = Assinatura confirmada!

# @p=memberMenu|subscribedAndItchUser @t=str
memberMenu--subscribedAndItchUser = Assinatura confirmada! (Propriedade no Itch verificada)

# @p=memberMenu|NotSubscribed @t=str
memberMenu--NotSubscribed = Nenhuma assinatura ativa detectada. Alguns recursos estão indisponíveis.

# @p=memberMenu|lastCheck @t=str
memberMenu--lastCheck = Última verificação:⎵

# @p=memberMenu|checkLatestVersion @t=str
memberMenu--checkLatestVersion = Procurando versão mais recente, por favor aguarde...

# @p=memberMenu|isLatestVersion @t=str
memberMenu--isLatestVersion = Você já está na versão mais recente!

# @p=memberMenu|notSponsor @t=str
memberMenu--notSponsor = Usuários não verificados devem se inscrever primeiro!

# @p=memberMenu|ImoutoFavorite @t=str
memberMenu--ImoutoFavorite = O(A) Favorito(a) da Imouto

# @p=memberMenu|itchUser @t=str
memberMenu--itchUser = Usuário do Itch confirmado!

# @p=memberMenu|nonItchUser @t=str
memberMenu--nonItchUser = Este jogo não foi encontrado na sua biblioteca do Itch!

# @p=memberMenu|itchVerifyNotice @t=str
memberMenu--itchVerifyNotice = Você pode verificar a propriedade da versão do Itch aqui

# @p=memberMenu|itchVerifyAlert @t=str
memberMenu--itchVerifyAlert = Por favor, faça login antes de verificar a versão do Itch!

# @p=memberMenu|majorUpdateFailed @t=array
memberMenu--majorUpdateFailed =
    Falha na atualização da versão principal!
    Código de erro: {"${}"}
    Tente fazer o login para verificação e iniciar a atualização novamente,
    ou envie esta print em nosso servidor do Discord para assistência!

# @p=AdventurersPathway|mapName @t=str
AdventurersPathway--mapName = ⎵ – Caminho do Aventureiro –⎵

# @p=ShallowRuinsLabyrinth|mapName @t=str
ShallowRuinsLabyrinth--mapName = – Labirinto das Ruínas Rasas –

# @p=ShallowRuinsLabyrinth|mapDescription @t=str
ShallowRuinsLabyrinth--mapDescription = Um vasto labirinto repleto de inúmeros mistérios⎵

# @p=ForgottenCatacombe|mapName @t=str
ForgottenCatacombe--mapName = ⎵– Catacumba Esquecida – ⏎n

# @p=ForestofRuins|mapName @t=str
ForestofRuins--mapName = ⎵– Floresta das Ruínas –⎵

# @p=AbandonedForest|mapName @t=str
AbandonedForest--mapName = ⎵– Floresta Abandonada –⎵

# @p=ExcavationSite|mapName @t=str
ExcavationSite--mapName = ⎵– Sítio de Escavação –⎵

# @p=TheFallenChurch|mapName @t=str
TheFallenChurch--mapName = ⎵– A Igreja Caída –⎵

# @p=DoorofStar|mapName @t=str
DoorofStar--mapName = ⎵– Porta da Estrela –⎵

# @p=ScorchingLavaZone|mapName @t=str
ScorchingLavaZone--mapName = – Zona de Lava Escaldante –

# @p=ScorchingLavaZone|mapDescription @t=str
ScorchingLavaZone--mapDescription = ⎵Uma terra ardente entrelaçada pelo fogo, onde as provações queimam eternamente⎵

# @p=Nibelungen|mapName @t=str
Nibelungen--mapName = ⎵– Nibelungen –⎵
