# Auto-generated by json_to_ftl.py

# @k=gameTitle @t=array
gameTitle = Uma Vida Simples com Minha Imouto Discreta⎵

# @k=goldHeld @t=array
goldHeld = Ouro

# @k=quantityHeld @t=array
quantityHeld = \fs[16]•Quantidade Possuída:\c[17] {"${}"} \c[0]\py[-8]

# @k=autoUpdate @t=array
autoUpdate =
    Atualização disponível: Dados do jogo da versão {"${}"} detectados.⎵
    Gostaria de baixar e atualizar agora?

# @k=fullScreen @t=array
fullScreen = Tela Cheia

# @k=masterVolume @t=array
masterVolume = Volume Geral

# @k=voiceVolume @t=array
voiceVolume = Volume da Voz

# @k=BgmVolume @t=array
BgmVolume = Volume da Música

# @k=BgsVolume @t=array
BgsVolume = Volume do Ambiente

# @k=SeVolume @t=array
SeVolume = Volume dos Efeitos Sonoros

# @k=MaxPlayerMsgs @t=array
MaxPlayerMsgs = Máx. de Mensagens por Jogador

# @k=GameFAQ @t=array
GameFAQ = Guia do Jogo

# @k=ShowWeaponDurability @t=array
ShowWeaponDurability = Mostrar Durabilidade da Arma

# @k=DisableAutoUpdate @t=array
DisableAutoUpdate = Desativar Atualização Automática

# @k=LockedFPS @t=array
LockedFPS = Travar a 60 FPS

# @k=Language @t=array
Language = Idioma do Jogo

# @k=SwitchLanguage @t=array
SwitchLanguage =
    Mudança de idioma do jogo detectado!
    Reiniciando agora para aplicar as novas configurações de idioma!

# @k=ErrorReport @t=array
ErrorReport =
    Um erro ocorreu. Pedimos que relate o bug no servidor do Discord do NLCH.
    (Clique em "OK" para abrir o link de convite)
    (Anexe uma captura de tela do erro)

# @k=UpdateComplete1 @t=array
UpdateComplete1 =
    Atualização do jogo concluída!
    O jogo será reiniciado automaticamente após fechar esta janela.
    Você pode carregar o salvamento automático para continuar sua jornada!

# @k=UpdateComplete2 @t=array
UpdateComplete2 =
    Atualização do jogo concluída!
    O jogo será reiniciado em breve para aplicar a atualização!

# @k=RemindToUpdate @t=array
RemindToUpdate =
    Ocorreu um erro e o jogo está travado.
    Um patch mais recente está disponível—
    Por favor, use a atualização automática para corrigir o problema!

# @k=bagFull @t=array
bagFull = Limite de inventário excedido!

# @k=noStatusEffects @t=array
noStatusEffects = Sem efeitos de status!

# @k=unimplementedDoor @t=array
unimplementedDoor = Esta porta não vai abrir deste lado

# @k=zipUpdateComplete @t=array
zipUpdateComplete =
    Atualização instalada com sucesso.⎵
    Reiniciando o jogo para aplicar a atualização!

# @k=zipUpdateFail @t=array
zipUpdateFail =
    Erro ao extrair e instalar atualizações!
    Por favor, tente atualizar automaticamente novamente ou
    extraia manualmente os arquivos da atualização para instalar!

# @k=fileDownloadedSuccessfully @t=array
fileDownloadedSuccessfully = {"${}"} baixado com sucesso!

# @k=fileDownloadFailed @t=array
fileDownloadFailed = {"${}"} falhou ao baixar! Tente novamente agora!

# @k=installPatch @t=array
installPatch = A atualização requer extração — instalando agora. Isso pode causar lentidão no jogo, por favor, seja paciente!

# @k=totalFilesToUpdate @t=array
totalFilesToUpdate = Foram detectados {"${}"} arquivo(s) para atualizar — começando a baixar os arquivos!

# @k=silentUpdateSuccess @t=array
silentUpdateSuccess = Novo patch de conteúdo para {"${}"} foi instalado com sucesso e entrará em vigor na próxima reinicialização.

# @k=outdatedVersionWarning @t=array
outdatedVersionWarning =
    Sua atual versão do jogo está desatualizada. A versão mais recente é {"${}"}.
    Atualizações de versão principal não suportam atualizações automáticas.⎵
    Por favor, baixe o jogo novamente de uma fonte oficial.

# @k=renameCharacter @t=array
renameCharacter =
    Lembrei agora—
    ela é...

# @k=heroName @t=array
heroName = Onii-chan

# @k=heroineName @t=array
heroineName = Imouto

# @k=nonHardwareAccelerated @t=array
nonHardwareAccelerated =
    O jogo está sendo executado na placa gráfica integrada!
    Se o seu PC tiver uma GPU dedicada, recomendamos configurar o Game.exe⎵
    para usá-la no painel de controle gráfico para uma experiência de jogo mais fluida.

# @k=isAmdCPU @t=array
isAmdCPU =
    Seu CPU foi identificado como um processador AMD.
    Alguns processadores AMD podem ter queda de quadros ao reproduzir vídeos VP9 (WebM)⎵
    em um ambiente Chromium. Se você encontrar esse problema, tente forçar o jogo
    a usar renderização via GPU ou atualize seus drivers para ajudar a amenizar a situação.

# @k=failedToLoad @t=array
failedToLoad =
    Este tipo de problema pode ser causado por:
    ① Arquivos do jogo corrompidos ou nomes de arquivos ilegíveis devido a problemas de codificação durante a extração/instalação.
    ② O desenvolvedor esqueceu de incluir o arquivo — aguarde uma atualização/patch para corrigir o problema.

# @k=LowResMode @t=array
LowResMode = Modo Gráfico Baixo

# @k=lowResModeWarning @t=array
lowResModeWarning =
    Essa função melhora o desempenho em dispositivos Android, essa função deve ter pouco ou nenhum efeito na versão de PC.
    Quando ativada, o jogo renderiza mapas e imagens em uma resolução mais baixa e então faz o upscaling,⎵
    reduzindo a carga da GPU em dispositivos móveis, baixando a temperatura e consumo de bateria.
    Nota: Essa é uma função experimental e sua eficiência pode variar dependendo do dispositivo.
    Você pode desabilitar essa função a qualquer momento para restaurar imediatamente a resolução da imagem.

# @k=cloudSaveServiceWarning @t=array
cloudSaveServiceWarning =
    Como o banco de dados de save da nuvem ainda está em construção,
    este recurso temporariamente solicitará acesso ao seu Google Drive
    para poder armazenar os arquivos de salvamento do jogo na pasta NLCH/save.
    Arquivos de save enviados serão usados somente para futura sincronização e⎵
    restaurá-los de volta ao jogo e não serão usados para quaisquer outros fins.
    Você concorda em conceder ao jogo acesso ao Google Drive?

# @k=uploadSaveFile @t=array
uploadSaveFile =
    Baixar um arquivo de salvamento do Google Drive substituirá os dados de salvamento locais atuais!
    Você deseja continuar?

# @k=nearbyMonstersCount @t=array
nearbyMonstersCount = Monstro detectado nas proximidades

# @k=nearbyTreasuresCount @t=array
nearbyTreasuresCount = Tesouro detectado nas proximidades

# @k=underwaterTreasuresCount @t=array
underwaterTreasuresCount = Tesouro submerso detectado nas proximidades

# @k=steamWishlist @t=array
steamWishlist =
    Nossa página na loja da Steam finalmente está ativa!
    Por favor, adicione-nos a sua lista de desejos e apoie-nos! (*´∀`)~♥
    ⬇Clique abaixo para abrir a página da Steam.

# @k=memberMenu @t=object @f=firstTimeNotice=array shortHint=str waitingLogin=str notLoggedIn=str RequestingLogin=str openingWindow=str cloudSave=str logInFirst=str CheckUpdates=str Subscribed=str subscribedAndItchUser=str NotSubscribed=str lastCheck=str checkLatestVersion=str isLatestVersion=str notSponsor=str ImoutoFavorite=str itchUser=str nonItchUser=str itchVerifyNotice=str itchVerifyAlert=str majorUpdateFailed=array
memberMenu = {""}
    .firstTimeNotice =
        Esta funcionalidade de verificação de propriedade está atualmente em fase experimental.
        Você pode entrar com o Patreon aqui,⎵
        ou vincular sua conta do Itch para verificação de propriedade.
        Se você tiver uma assinatura ativa
        ou já possuir o jogo no Itch,
        poderá usar recursos como atualização automática de grandes atualizações.
        
        Observação:
        No momento, a verificação está disponível apenas para jogadores⎵
        que compraram o jogo no Itch ou no Patreon,⎵
        ou para jogadores com uma assinatura paga no Patreon.
    .shortHint = ⎵Agora é possível ativar salvamentos na nuvem e grandes atualizações
    .waitingLogin = Aguardando a conclusão do login...
    .notLoggedIn = Não está logado
    .RequestingLogin = Solicitando link de login...
    .openingWindow = Abrindo janela de login no Patreon...
    .cloudSave = Usar Salvamento na Nuvem
    .logInFirst = Por favor, clique neste botão para entrar primeiro
    .CheckUpdates = Atualize para a versão mais recente
    .Subscribed = Assinatura confirmada!
    .subscribedAndItchUser = Assinatura confirmada! (Propriedade no Itch verificada)
    .NotSubscribed = Nenhuma assinatura ativa detectada. Alguns recursos estão indisponíveis.
    .lastCheck = Última verificação:⎵
    .checkLatestVersion = Procurando versão mais recente, por favor aguarde...
    .isLatestVersion = Você já está na versão mais recente!
    .notSponsor = Usuários não verificados devem se inscrever primeiro!
    .ImoutoFavorite = O(A) Favorito(a) da Imouto
    .itchUser = Usuário do Itch confirmado!
    .nonItchUser = Este jogo não foi encontrado na sua biblioteca do Itch!
    .itchVerifyNotice = Você pode verificar a propriedade da versão do Itch aqui
    .itchVerifyAlert = Por favor, faça login antes de verificar a versão do Itch!
    .majorUpdateFailed =
        Falha na atualização da versão principal!
        Código de erro: {"${}"}
        Tente fazer o login para verificação e iniciar a atualização novamente,
        ou envie esta print em nosso servidor do Discord para assistência!

# @k=AdventurersPathway @t=object @f=mapName=str
AdventurersPathway = {""}
    .mapName = ⎵ – Caminho do Aventureiro –⎵

# @k=ShallowRuinsLabyrinth @t=object @f=mapName=str mapDescription=str
ShallowRuinsLabyrinth = {""}
    .mapName = – Labirinto das Ruínas Rasas –
    .mapDescription = Um vasto labirinto repleto de inúmeros mistérios⎵

# @k=ForgottenCatacombe @t=object @f=mapName=str
ForgottenCatacombe = {""}
    .mapName = ⎵– Catacumba Esquecida – ⏎n

# @k=ForestofRuins @t=object @f=mapName=str
ForestofRuins = {""}
    .mapName = ⎵– Floresta das Ruínas –⎵

# @k=AbandonedForest @t=object @f=mapName=str
AbandonedForest = {""}
    .mapName = ⎵– Floresta Abandonada –⎵

# @k=ExcavationSite @t=object @f=mapName=str
ExcavationSite = {""}
    .mapName = ⎵– Sítio de Escavação –⎵

# @k=TheFallenChurch @t=object @f=mapName=str
TheFallenChurch = {""}
    .mapName = ⎵– A Igreja Caída –⎵

# @k=DoorofStar @t=object @f=mapName=str
DoorofStar = {""}
    .mapName = ⎵– Porta da Estrela –⎵

# @k=ScorchingLavaZone @t=object @f=mapName=str mapDescription=str
ScorchingLavaZone = {""}
    .mapName = – Zona de Lava Escaldante –
    .mapDescription = ⎵Uma terra ardente entrelaçada pelo fogo, onde as provações queimam eternamente⎵

# @k=Nibelungen @t=object @f=mapName=str
Nibelungen = {""}
    .mapName = ⎵– Nibelungen –⎵
